### ISSUE TITLE
ignore up/down interface during --mode interface-health

### ISSUE THREAD

**Issue by talbaror** [lausser/check_nwc_health#100]
Hello,

I am using the "--mode interface-health" advantage with that service that he gives all interface health condition, the issue with that mode is all interface that is down its raising critical condition
I would like to ignore for now all up/down interface status.
My question is there a way to ignore during check and override its output status only for the UP/DOWN status?
Please advise
Thanks

**Comment by lausser** [comment]
Sorry, this is not possible.

**Comment by talbaror** [comment]
thanks
