### ISSUE TITLE
support ngfw stonesoft/forcepoint

### ISSUE THREAD

**Issue by trentasis** [lausser/check_nwc_health#105]
Hi

I like to know if it is possible toadd support to monitor ngfw firewalls from stonesoft / forcepoint...
I have fou d snmp mibs in
http://help.stonesoft.com/onlinehelp/StoneGate/SMC/5.10.1/GUID-6D0B949F-CA4E-4EEF-BAB4-AF7C248D9EB7.html
https://my.stonesoft.com/support/browse.do?product=StoneGate&browsetype=subject&selection=SNMP

How can we add this feature like other Fw that chech nwc is supported?

thanks

**Comment by trentasis** [comment]
Any scheduled date or how to implement?

**Comment by andytlc68** [comment]
Hello! I woukd like to know if there are some news for this topic. I too would need to monitor Forcepoint NGFW ... and I know that even with the new version of check_nwc_health (10.0.0.2) it is not possible to have data on cpu, mem, hardware health.
Thanks!!
