### ISSUE TITLE
please add Juniper / SRX

### ISSUE THREAD

**Issue by ClemensBW** [lausser/check_nwc_health#119]
MIB Name MIB
exampe output xyz for this mib

 
MIB Maximum CP Session availability	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.1 = Gauge32: 1048576

jnxJsSPUMonitoringIndex jnxJsSPUMonitoringIndex 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.1 = No Such Object available on this agent at this OID

jnxJsSPUMonitoringNodeIndex jnxJsSPUMonitoringNodeIndex 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.10
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.9 = Gauge32: 1

jnxJsSPUMonitoringNodeDescr jnxJsSPUMonitoringNodeDescr 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.11
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.1 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.9 = STRING: "node1"

jnxJsSPUMonitoringFPCIndex jnxJsSPUMonitoringFPCIndex 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.2
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.9 = Gauge32: 1

jnxJsSPUMonitoringSPUIndex jnxJsSPUMonitoringSPUIndex 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.3
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.9 = Gauge32: 0

jnxJsSPUMonitoringCPUUsage jnxJsSPUMonitoringCPUUsage 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.4
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.1 = Gauge32: 43
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.9 = Gauge32: 1

jnxJsSPUMonitoringMemoryUsage jnxJsSPUMonitoringMemoryUsage 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.5
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.1 = Gauge32: 80
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.9 = Gauge32: 71

jnxJsSPUMonitoringCurrentFlowSession jnxJsSPUMonitoringCurrentFlowSession 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.6
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.1 = Gauge32: 95442
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.9 = Gauge32: 99177

jnxJsSPUMonitoringMaxFlowSession jnxJsSPUMonitoringMaxFlowSession 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.7
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.9 = Gauge32: 1048576

jnxJsSPUMonitoringCurrentCPSession jnxJsSPUMonitoringCurrentCPSession 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.8
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.1 = Gauge32: 97299
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.9 = Gauge32: 96951

jnxJsSPUMonitoringMaxCPSession jnxJsSPUMonitoringMaxCPSession 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1.9
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.9 = Gauge32: 1048576

jnxJsSPUMonitoringCurrentTotalSession jnxJsSPUMonitoringCurrentTotalSession 	1.3.6.1.4.1.2636.3.39.1.12.1.2
iso.3.6.1.4.1.2636.3.39.1.12.1.2.0 = Gauge32: 98249

jnxJsSPUMonitoringMaxTotalSession jnxJsSPUMonitoringMaxTotalSession 	1.3.6.1.4.1.2636.3.39.1.12.1.3
iso.3.6.1.4.1.2636.3.39.1.12.1.3.0 = Gauge32: 1048576

jnxSPUClusterObjectsTable jnxSPUClusterObjectsTable 	1.3.6.1.4.1.2636.3.39.1.12.1.4
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.0 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.1 = STRING: "node1"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.0 = Gauge32: 96408
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.1 = Gauge32: 98500
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.0 = Counter64: 1178
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.6.0 = Counter64: 1178
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.6.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.7.0 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.7.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.8.0 = Gauge32: 96408
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.8.1 = Gauge32: 98500
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.9.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.9.1 = Gauge32: 0

jnxSPUClusterObjectsEntry jnxSPUClusterObjectsEntry 	1.3.6.1.4.1.2636.3.39.1.12.1.4.1
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.0 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.1 = STRING: "node1"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.0 = Gauge32: 96344
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.1 = Gauge32: 98393
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.0 = Counter64: 1176
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.6.0 = Counter64: 1176
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.6.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.7.0 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.7.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.8.0 = Gauge32: 96344
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.8.1 = Gauge32: 98393
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.9.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.9.1 = Gauge32: 0

jnxJsClusterMonitoringNodeIndex jnxJsClusterMonitoringNodeIndex 	1.3.6.1.4.1.2636.3.39.1.12.1.4.1.1
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.1 = Gauge32: 1

jnxJsClusterMonitoringNodeDescr jnxJsClusterMonitoringNodeDescr 	1.3.6.1.4.1.2636.3.39.1.12.1.4.1.2
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.0 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.1 = STRING: "node1"

jnxJsNodeCurrentTotalSession jnxJsNodeCurrentTotalSession 	1.3.6.1.4.1.2636.3.39.1.12.1.4.1.3
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.0 = Gauge32: 95848
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.1 = Gauge32: 96546

jnxJsNodeMaxTotalSession jnxJsNodeMaxTotalSession 	1.3.6.1.4.1.2636.3.39.1.12.1.4.1.4
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.1 = Gauge32: 1048576

jnxJsNodeSessionCreationPerSecond jnxJsNodeSessionCreationPerSecond 	1.3.6.1.4.1.2636.3.39.1.12.1.4.1.5
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.0 = Counter64: 1121
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.1 = Counter64: 0

jnxJsSPUMonitoringMIB jnxJsSPUMonitoringMIB 	1.3.6.1.4.1.2636.3.39.1.12.1 (summary)
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.1 = Gauge32: 39
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.1 = Gauge32: 80
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.9 = Gauge32: 71
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.1 = Gauge32: 91411
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.9 = Gauge32: 95789
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.9 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.1 = Gauge32: 93526
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.9 = Gauge32: 95501
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.9 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.1 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.9 = STRING: "node1"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.12.1 = Gauge32: 91411
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.12.9 = Gauge32: 94380
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.13.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.13.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.14.1 = Gauge32: 93526
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.14.9 = Gauge32: 94171
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.15.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.15.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.2.0 = Gauge32: 94380
iso.3.6.1.4.1.2636.3.39.1.12.1.3.0 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.1.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.0 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.2.1 = STRING: "node1"
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.0 = Gauge32: 93526
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.3.1 = Gauge32: 94380
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.4.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.0 = Counter64: 1116
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.6.0 = Counter64: 1116
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.6.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.7.0 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.7.1 = Counter64: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.8.0 = Gauge32: 93526
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.8.1 = Gauge32: 94380
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.9.0 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.4.1.9.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.5.0 = Gauge32: 94380
iso.3.6.1.4.1.2636.3.39.1.12.1.6.0 = Gauge32: 0

jnxJsSPUMonitoringObjectsTable jnxJsSPUMonitoringObjectsTable 	1.3.6.1.4.1.2636.3.39.1.12.1.1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.1 = Gauge32: 43
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.1 = Gauge32: 80
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.9 = Gauge32: 71
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.1 = Gauge32: 94306
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.9 = Gauge32: 97574
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.9 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.1 = Gauge32: 96499
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.9 = Gauge32: 97295
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.9 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.1 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.9 = STRING: "node1"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.12.1 = Gauge32: 94306
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.12.9 = Gauge32: 97574
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.13.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.13.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.14.1 = Gauge32: 97662
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.14.9 = Gauge32: 97295
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.15.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.15.9 = Gauge32: 0

jnxJsSPUMonitoringObjectsEntry jnxJsSPUMonitoringObjectsEntry 	1.3.6.1.4.1.2636.3.39.1.12.1.1.1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.1 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.2.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.3.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.1 = Gauge32: 40
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.1 = Gauge32: 80
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.9 = Gauge32: 71
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.1 = Gauge32: 93984
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.9 = Gauge32: 96217
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.7.9 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.1 = Gauge32: 96159
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.9 = Gauge32: 95779
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.1 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.9.9 = Gauge32: 1048576
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.10.9 = Gauge32: 1
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.1 = STRING: "node0"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.11.9 = STRING: "node1"
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.12.1 = Gauge32: 93984
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.12.9 = Gauge32: 96217
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.13.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.13.9 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.14.1 = Gauge32: 96159
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.14.9 = Gauge32: 95779
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.15.1 = Gauge32: 0
iso.3.6.1.4.1.2636.3.39.1.12.1.1.1.15.9 = Gauge32: 0

jnxFilledDescr 	1.3.6.1.4.1.2636.3.1.12.1.5
iso.3.6.1.4.1.2636.3.1.12.1.5.1.1.0.0 = STRING: "node0, chassis frame"
iso.3.6.1.4.1.2636.3.1.12.1.5.1.2.0.0 = STRING: "node1, chassis frame"
iso.3.6.1.4.1.2636.3.1.12.1.5.2.1.0.0 = STRING: "node0, PEM slot 0"
iso.3.6.1.4.1.2636.3.1.12.1.5.2.2.0.0 = STRING: "node0, PEM slot 1"
iso.3.6.1.4.1.2636.3.1.12.1.5.2.3.0.0 = STRING: "node1, PEM slot 0"
iso.3.6.1.4.1.2636.3.1.12.1.5.2.4.0.0 = STRING: "node1, PEM slot 1"
iso.3.6.1.4.1.2636.3.1.12.1.5.4.1.0.0 = STRING: "node0, Fan Tray slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.4.1.1.0 = STRING: "node0, Fan 1 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.4.1.2.0 = STRING: "node0, Fan 2 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.4.2.0.0 = STRING: "node1, Fan Tray slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.4.2.1.0 = STRING: "node1, Fan 1 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.4.2.2.0 = STRING: "node1, Fan 2 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.1.0.0 = STRING: "node0, FPC slot 0"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.2.0.0 = STRING: "node0, FPC slot 1"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.3.0.0 = STRING: "node0, FPC slot 2"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.4.0.0 = STRING: "node0, FPC slot 3"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.5.0.0 = STRING: "node1, FPC slot 0"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.6.0.0 = STRING: "node1, FPC slot 1"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.7.0.0 = STRING: "node1, FPC slot 2"
iso.3.6.1.4.1.2636.3.1.12.1.5.7.8.0.0 = STRING: "node1, FPC slot 3"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.1.1.0 = STRING: "node0, PIC slot @ 0/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.2.1.0 = STRING: "node0, PIC slot @ 1/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.3.1.0 = STRING: "node0, PIC slot @ 2/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.4.1.0 = STRING: "node0, PIC slot @ 3/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.5.1.0 = STRING: "node1, PIC slot @ 0/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.6.1.0 = STRING: "node1, PIC slot @ 1/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.7.1.0 = STRING: "node1, PIC slot @ 2/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.8.8.1.0 = STRING: "node1, PIC slot @ 3/0/*"
iso.3.6.1.4.1.2636.3.1.12.1.5.9.1.0.0 = STRING: "node0, Routing Engine 0 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.9.2.0.0 = STRING: "node0, Routing Engine 1 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.9.3.0.0 = STRING: "node1, Routing Engine 0 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.9.4.0.0 = STRING: "node1, Routing Engine 1 slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.10.1.1.0 = STRING: "node0, FPM Board slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.10.2.1.0 = STRING: "node1, FPM Board slot"
iso.3.6.1.4.1.2636.3.1.12.1.5.12.1.0.0 = STRING: "node0, CB slot 0"
iso.3.6.1.4.1.2636.3.1.12.1.5.12.2.0.0 = STRING: "node0, CB slot 1"
iso.3.6.1.4.1.2636.3.1.12.1.5.12.3.0.0 = STRING: "node1, CB slot 0"
iso.3.6.1.4.1.2636.3.1.12.1.5.12.4.0.0 = STRING: "node1, CB slot 1"

jnxFilledChassisId 	1.3.6.1.4.1.2636.3.1.12.1.7
iso.3.6.1.4.1.2636.3.1.12.1.6.1.1.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.1.2.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.2.1.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.2.2.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.2.3.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.2.4.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.4.1.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.4.1.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.4.1.2.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.4.2.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.4.2.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.4.2.2.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.7.1.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.7.2.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.7.3.0.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.7.4.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.7.5.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.7.6.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.7.7.0.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.7.8.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.8.1.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.8.2.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.8.3.1.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.8.4.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.8.5.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.8.6.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.8.7.1.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.8.8.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.9.1.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.9.2.0.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.9.3.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.9.4.0.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.10.1.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.10.2.1.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.12.1.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.12.2.0.0 = INTEGER: 2
iso.3.6.1.4.1.2636.3.1.12.1.6.12.3.0.0 = INTEGER: 3
iso.3.6.1.4.1.2636.3.1.12.1.6.12.4.0.0 = INTEGER: 2

More doc at: https://kb.juniper.net/library/CUSTOMERSERVICE/GLOBAL_JTAC/BK26199/SRX%20SNMP%20Monitoring%20Guide.pdf

If you like I can send more snmp debug info.

regards
Clemens

**Comment by lausser** [comment]
SRX has been added since v5.11

**Comment by ClemensBW** [comment]
Hello,
don't work at my box (SRX1400 with JUNOS 12.1) with check_nwc_health $Revision: 5.11.3 :/

snmpwalk -v3 -u xyz-a SHA -l authPriv -A XXX-x AES -X ZYX 10.1.2.3
iso.3.6.1.2.1.1.1.0 = STRING: "Juniper Networks, Inc. srx1400 internet router, kernel JUNOS 12.1X46-D40.2 #0: 2015-09-26 03:22:03 UTC     builder@greteth.juniper.net:/volume/build/junos/12.1/service/12.1X46-D40.2/obj-powerpc/junos/bsd/kernels/JUNIPER-SRX/kernel Build date: 2015-09-26 "


mode uptime or interface-usage works fine, but hardware-health, session-usage, cpu-load, fw-connections or memory-usage and a few other checks it only say: "Mode hardware-health is not implemented for this type of device".

**Comment by ClemensBW** [comment]
Hello,
Juniper say, that the MIB 1.3.6.1.4.1.2636.3.1.13.1.19 has only hexa-decimal output. Is it possible that you use MIB 1.3.6.1.4.1.2636.3.1.13.1.13 (jnxOperatingUpTime), this is the same in integer.
