### ISSUE TITLE
Support for pool checks not working if BIG-IP software release 12.x

### ISSUE THREAD

**Issue by abzeidler** [lausser/check_nwc_health#121]
Hi,

we're seeing an issue with pool checks, if the Big-IP is running software version12.x.

The following checks don't work properly:
--mode
pool-completeness
pool-connections
pool-complections
list-pools

We're running:
check_nwc_health $Revision: 5.11.3 $ [http://labs.consol.de/nagios/check_nwc_health]

and the issue seems to be related to this line:
31021:      $self->{sysProductVersion} !~ /^((9)|(10)|(11))/) {

After extending the expression to include version 12 the check works.

Kind regards,

Björn

**Comment by lausser** [comment]
has just been pushed
