### ISSUE TITLE
Use of uninitialized value when use interface availability

### ISSUE THREAD

**Issue by blastkiller-** [lausser/check_nwc_health#137]
When using command:

 **~/local/lib/nagios/plugins/check_nwc_health -H x.x.x.x -C public --mode interface-availability** 

on a HP network switch i get following error mesage:

**Use of uninitialized value $_ in split at /omd/sites/network/local/lib/nagios/plugins/check_nwc_health line 4940.
Use of uninitialized value $_ in split at /omd/sites/network/local/lib/nagios/plugins/check_nwc_health line 4940.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/SNMP.pm line 1416.
Use of uninitialized value $_[0] in sprintf at /usr/share/perl5/Net/SNMP.pm line 3095.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/SNMP.pm line 1416.
Use of uninitialized value $_[0] in sprintf at /usr/share/perl5/Net/SNMP.pm line 3095.
Use of uninitialized value $_ in pattern match (m//) at /usr/share/perl5/Net/SNMP.pm line 1416.
Use of uninitialized value $_[0] in sprintf at /usr/share/perl5/Net/SNMP.pm line 3095.**

The last version all working is 6.0.1.2

**Comment by lausser** [comment]
Can you please run 
check_nwc_health .... --mode walk | bash
and mail me the resulting snmpwalk-file to gerhard.lausser@consol.de
With this file i can simulate your HP.

**Comment by lausser** [comment]
in a few minutes you should see a 6.2.1.3 on [https://labs.consol.de/nagios/check_nwc_health/index.html](https://labs.consol.de/nagios/check_nwc_health/index.html)

**Comment by blastkiller-** [comment]
Thanks a lot for the fix. Working now.

**Comment by sikaleska** [comment]
Hi,
The same error appears in the last version. Can you please tell me what is the solution?

Info:    Use of uninitialized value in pattern match (m//) at /usr/lib64/nagios/plugins/check_nwc_health line 90143.
Use of uninitialized value in pattern match (m//) at /usr/lib64/nagios/plugins/check_nwc_health line 90149.
Use of uninitialized value in pattern match (m//) at /usr/lib64/nagios/plugins/check_nwc_health line 90185.
Use of uninitialized value in pattern match (m//) at /usr/lib64/nagios/plugins/check_nwc_health line 90189.
Use of uninitialized value $sysobj in substitution (s///) at /usr/lib64/nagios/plugins/check_nwc_health line 4198.
1 of 4 (3 adm. up) interfaces are available <table style="border-collapse:collapse; border: 1px solid black;"><tr><th style="text-align: right; padding-left: 4px; padding-right: 6px;">Index</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">Descr</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">Type</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">Speed</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">AdminStatus</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">OperStatus</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">Duration</th><th style="text-align: right; padding-left: 4px; padding-right: 6px;">Available</th></tr><tr><tr style="border: 1px solid black;"><td style="text-align: right; padding-left: 4px; padding-right: 6px;">1</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">lo</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">so  ftwareLoopback</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">10MB</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">up</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">up</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">46d 18h 8m 27s</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">false</td></tr><tr><tr style="border: 1px solid black;"><td style="text-align: right; padding-left: 4px; padding-right: 6px;">2</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">eth0</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">ethernetCsmacd</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">1GB</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">up</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">up</td><td style="text-align: right; padding-left: 4px; paddi
 ng-right: 6px;">46d 18h 8m 27s</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">false</td></tr><tr><tr style="border: 1px solid black;"><td style="text-align: right; padding-left: 4px; padding-right: 6px;">3</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">eth1</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">ethernetCsmacd</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">1GB</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">up</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">up</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">46d 18h 6m 27s</td><td style="text-align: right; padding-left: 4px; padding-right: 6px;">false</td></tr><tr><tr style="border: 1px solid black;"><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">4</td><td style="text-align: right; padding-left
 : 4px; padding-right: 6px; background-color: #00ff33;">sit0</td><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">tunnel</td><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">0B</td><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">down</td><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">down</td><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">46d 18h 8m 27s</td><td style="text-align: right; padding-left: 4px; padding-right: 6px; background-color: #00ff33;">true</td></tr></table>
<!--
