### ISSUE TITLE
RADLANMIB.pm needed by `check_nwc_health'

### ISSUE THREAD

**Issue by d-zalewski** [lausser/check_nwc_health#140]
`root:~> git clone https://github.com/lausser/check_nwc_health
Initialized empty Git repository in /root/check_nwc_health/.git/
remote: Counting objects: 8507, done.
remote: Total 8507 (delta 0), reused 0 (delta 0), pack-reused 8507
Receiving objects: 100% (8507/8507), 8.86 MiB | 3.42 MiB/s, done.
Resolving deltas: 100% (5248/5248), done.

root:~> git submodule init
fatal: Not a git repository (or any of the parent directories): .git

root:~> cd check_nwc_health/

root:~/check_nwc_health> git submodule init
Submodule 'GLPlugin' (git://github.com/lausser/GLPlugin.git) registered for path 'GLPlugin'

root:~/check_nwc_health> git submodule update
Initialized empty Git repository in /root/check_nwc_health/GLPlugin/.git/
remote: Counting objects: 2090, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 2090 (delta 15), reused 28 (delta 9), pack-reused 2052
Receiving objects: 100% (2090/2090), 1.05 MiB | 1.29 MiB/s, done.
Resolving deltas: 100% (1102/1102), done.
Submodule path 'GLPlugin': checked out 'f96f2c8ee8233193586b79781f308e20d2697297'

invldnvlmonw1:root:~/check_nwc_health> autoreconf
Makefile.am:4: shell which dos2unix || which fromdos: non-POSIX variable name
Makefile.am:4: (probably a GNU make extension)

invldnvlmonw1:root:~/check_nwc_health> ./configure;make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for sh... /bin/sh
checking for perl... /usr/local/bin/perl
configure: creating ./config.status
config.status: creating Makefile
config.status: creating plugins-scripts/Makefile
config.status: creating plugins-scripts/subst
                       --with-perl: /usr/local/bin/perl
                --with-nagios-user: nagios
               --with-nagios-group: nagios
              --disable-standalone:
Making all in plugins-scripts
make[1]: Entering directory `/root/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target `../GLPlugin/lib/Monitoring/GLPlugin/SNMP/MibsAndOids/RADLANMIB.pm', needed by `check_nwc_health'.  Stop.
make[1]: Leaving directory `/root/check_nwc_health/plugins-scripts'
make: *** [all-recursive] Error 1
`

**Comment by lausser** [comment]
git pull
and it should be ok now.
Gerhard
