### ISSUE TITLE
feature request for --nodownports or similar on perf data return

### ISSUE THREAD

**Issue by jediblair** [lausser/check_nwc_health#148]
In the interface-usage and interface-errors mode, I would like to see an extra command line option which will only return performance data for ports which are operationally up.
 
Reason being I have a lot of switch stacks where all the ports are Admin Up but only a few ports are actually used. returning performance data for down ports causes a crapload of extra storage in my backend for no useful benefit. I've already got a workaround for this in place but not implemented as a proper command line option, so no urgency on this. Just would be nice to see it done properly.

**Comment by lausser** [comment]
You can add
--name _operup_

**Comment by lausser** [comment]
Arrghhh, not italic. it's
``--name _operup_

**Comment by lausser** [comment]
Hundsglump varreckts!!!!
`--name _operup_`

**Comment by lausser** [comment]
And to know which ports have been disconnected although they shouldn't:
`--mode interface-status --name _adminup_`
