### ISSUE TITLE
make is not possible

### ISSUE THREAD

**Issue by crsprsp** [lausser/check_nwc_health#160]
Hi, 

A make of the current gitmaster fails:

Making all in plugins-scripts
make[1]: Entering directory '/usr/src/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target 'Classes/HOSTRESOURCESMIB/Component/ClockSubsystem.pm', needed by 'check_nwc_health'.  Stop.
make[1]: Leaving directory '/usr/src/check_nwc_health/plugins-scripts'
Makefile:341: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

the ClockSubsystem.pm fails.

bye, Rico

**Comment by lausser** [comment]
I just pushed the missing module.
