### ISSUE TITLE
interface-health and icinga2

### ISSUE THREAD

**Issue by rahonalab** [lausser/check_nwc_health#161]
I am currently monitoring a series of devices (hp procurve switch, cisco 2960 switch, fortigate firewall) with check_nwc_health and it works fine, with the exception of interface-health mode. 
With icinga2, sometimes the plugin works and finds the interfaces, other times it gives a 'no interfaces' unknown. I employ the following regexp: .* as nwc_health_name and the nwc_health_regexp is turned to TRUE; I have also set up a timeout of 60 seconds.
From the command line, the plugin works all the time, even without the --name flag

`/usr/lib/nagios/plugins/check_nwc_health  --hostname <hostname> --community <community> --mode interface-health`

**Comment by lausser** [comment]
We do not use Icinga2 at our customers installations, so i have no idea what happens.
You might add "-vvvvvvvvvvvvvv" to the command definition and check_nwc_health will produce a lot of internal debugging output. Maybe you can then see what goes wrong when communitcating with the devices.
