### ISSUE TITLE
cpu_tmm_usage  on f5   

### ISSUE THREAD

**Issue by gerizeltser** [lausser/check_nwc_health#168]
Hello,
can you please look at the error   
use check_nwc_health $Revision: 7.0.0.6 

[root@nagios_xi_stg plugins-scripts]# ./check_nwc_health  --hostname X.x.X.X --community X --mode cpu-load --timeout 60 --warning 85 --critical 95
Name "Data::Dumper::Sparseseen" used only once: possible typo at ./check_nwc_health line 972.
OK - tmm cpu usage is 39.67% | 'cpu_tmm_usage'=39.67%;85;95;0;100

in code 

use strict;
use IO::File;
use File::Basename;
use Digest::MD5 qw(md5_hex);
use Errno;
use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sparseseen = 1;
our $AUTOLOAD;
*VERSION = \'3.0.2';

use constant { OK => 0, WARNING => 1, CRITICAL => 2, UNKNOWN => 3 };

for now I   commented out    the    #$Data::Dumper::Sparseseen = 1;   and it run ok

**Comment by hvad** [comment]
Hi,
It fix in version 7.0.1.1.
see : 
  eval {
  # avoid "used only once" because older Data::Dumper don't have this
  # use OMD please because OMD has everything!
  no warnings 'all';
  $Data::Dumper::Sparseseen = 1;
};

**Comment by lausser** [comment]
yes, that was a problem with centos 6, which is still out there.
