### ISSUE TITLE
warningx and criticalx not taken into account for mode hardware-health

### ISSUE THREAD

**Issue by Tontonitch** [lausser/check_nwc_health#174]
Hello,

I discovered that the warningx and criticalx options are not taken into account for mode hardware-health, at least for my case:

```
[root@monitorsrv1 commands]# /usr/lib64/nagios/plugins/check_nwc_health --community xxxxxx --hostname xxxxxx --mode hardware-health --timeout 60 --warningx temp_1006=30
OK - environmental hardware working fine | 'temp_1006'=31;60;;;
[root@monitorsrv1 commands]#
```

version:
```
[root@monitorsrv1 commands]# /usr/lib64/nagios/plugins/check_nwc_health -V
check_nwc_health $Revision: 6.3.0.2 $ [http://labs.consol.de/nagios/check_nwc_health]
[root@monitorsrv1 commands]#
```

**Comment by lausser** [comment]
What do you get when you add a "-v"?

**Comment by Tontonitch** [comment]
```
[root@monitorsrv1 ~]# /usr/lib64/nagios/plugins/check_nwc_health --community xxxxxxxx --hostname xxxxxxxxxxx --mode hardware-health --timeout 60 --warningx temp_1006=20
OK - environmental hardware working fine | 'temp_1006'=23;60;;;
[root@monitorsrv1 ~]#
```

```
[root@monitorsrv1 ~]# /usr/lib64/nagios/plugins/check_nwc_health --community xxxxxxxx --hostname xxxxxxxxxxx --mode hardware-health --timeout 60 --warningx temp_1006=20 -v
I am a Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.2(1)E1, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Fri 22-Nov-13 06:27 by prod_rel_team
OK - environmental hardware working fine
checking fans
fan 1035 (Switch#1, Fan#1) is normal
fan 1037 (Switch#1, Fan#2) is normal
checking temperatures
temperature 1006 SW#1, Sensor#1, GREEN  is 23 (of 60 max = normal)
checking supplies
powersupply 1034 (Sw1, PS1 Normal, RPS NotExist) is normal
powersupply 1036 (Sw1, PS2 Normal, RPS NotExist) is normal
checking voltages | 'temp_1006'=23;60;;;
[root@monitorsrv1 ~]#

```

**Comment by lausser** [comment]
Sorry, i meant -vv Gesendet von meinem Windows 10 Phone Von:  <mailto:notifications@github.com> Yannick Charton
 Gesendet:  Freitag, 29. Juni 2018 17:48
 An:  <mailto:check_nwc_health@noreply.github.com> lausser/check_nwc_health
 Cc:  <mailto:Gerhard.Lausser@consol.de> Gerhard Lausser ;  <mailto:comment@noreply.github.com> Comment
 Betreff:  Re: [lausser/check_nwc_health] warningx and criticalx not taken into account for mode hardware-health (#174)```
[root@monitorsrv1 ~]# /usr/lib64/nagios/plugins/check_nwc_health --community xxxxxxxx --hostname xxxxxxxxxxx --mode hardware-health --timeout 60 --warningx temp_1006=20
OK - environmental hardware working fine | 'temp_1006'=23;60;;;
[root@monitorsrv1 ~]#
```

```
[root@monitorsrv1 ~]# /usr/lib64/nagios/plugins/check_nwc_health --community xxxxxxxx --hostname xxxxxxxxxxx --mode hardware-health --timeout 60 --warningx temp_1006=20 -v
I am a Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.2(1)E1, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Fri 22-Nov-13 06:27 by prod_rel_team
OK - environmental hardware working fine
checking fans
fan 1035 (Switch#1, Fan#1) is normal
fan 1037 (Switch#1, Fan#2) is normal
checking temperatures
temperature 1006 SW#1, Sensor#1, GREEN  is 23 (of 60 max = normal)
checking supplies
powersupply 1034 (Sw1, PS1 Normal, RPS NotExist) is normal
powersupply 1036 (Sw1, PS2 Normal, RPS NotExist) is normal
checking voltages | 'temp_1006'=23;60;;;
[root@monitorsrv1 ~]#

```

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/lausser/check_nwc_health/issues/174#issuecomment-401395333

**Comment by Tontonitch** [comment]
Below the requested info
```
[root@monitorsrv1 ~]# /usr/lib64/nagios/plugins/check_nwc_health --community xxxxxxxxx --hostname xxxxxxxxx --mode hardware-health --timeout 60 --warningx temp_1006=20 -vv
I am a Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.2(1)E1, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Fri 22-Nov-13 06:27 by prod_rel_team
[FANSUBSYSTEM]
info: checking fans

[FAN_1035]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#1, Fan#1
ciscoEnvMonFanStatusIndex: 1035
info: fan 1035 (Switch#1, Fan#1) is normal

[FAN_1037]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#1, Fan#2
ciscoEnvMonFanStatusIndex: 1037
info: fan 1037 (Switch#1, Fan#2) is normal

[TEMPERATURESUBSYSTEM]
info: checking temperatures

[TEMPERATURE_1006]
ciscoEnvMonTemperatureLastShutdown: 0
ciscoEnvMonTemperatureState: normal
ciscoEnvMonTemperatureStatusDescr: SW#1, Sensor#1, GREEN
ciscoEnvMonTemperatureStatusIndex: 1006
ciscoEnvMonTemperatureStatusValue: 22
ciscoEnvMonTemperatureThreshold: 60
info: temperature 1006 SW#1, Sensor#1, GREEN  is 22 (of 60 max = normal)

[POWERSUPPLYSUBSYSTEM]
info: checking supplies

[POWERSUPPLY_1034]
ciscoEnvMonSupplySource: ac
ciscoEnvMonSupplyState: normal
ciscoEnvMonSupplyStatusDescr: Sw1, PS1 Normal, RPS NotExist
ciscoEnvMonSupplyStatusIndex: 1034
info: powersupply 1034 (Sw1, PS1 Normal, RPS NotExist) is normal

[POWERSUPPLY_1036]
ciscoEnvMonSupplySource: ac
ciscoEnvMonSupplyState: normal
ciscoEnvMonSupplyStatusDescr: Sw1, PS2 Normal, RPS NotExist
ciscoEnvMonSupplyStatusIndex: 1036
info: powersupply 1036 (Sw1, PS2 Normal, RPS NotExist) is normal

[VOLTAGESUBSYSTEM]
info: checking voltages

OK - environmental hardware working fine
checking fans
fan 1035 (Switch#1, Fan#1) is normal
fan 1037 (Switch#1, Fan#2) is normal
checking temperatures
temperature 1006 SW#1, Sensor#1, GREEN  is 22 (of 60 max = normal)
checking supplies
powersupply 1034 (Sw1, PS1 Normal, RPS NotExist) is normal
powersupply 1036 (Sw1, PS2 Normal, RPS NotExist) is normal
checking voltages | 'temp_1006'=22;60;;;
[root@monitorsrv1 ~]#
```

**Comment by lausser** [comment]
```
ciscoEnvMonTemperatureState: normal
ciscoEnvMonTemperatureThreshold: 60
```
The "external" warning/critical is ignored here. We only look at the threshold which is set by the device itself.

**Comment by Tontonitch** [comment]
So, the "external" warning/critical (check_nwc_health warning/warningx/critical/criticalx parameters) are ignored when there is a threshold already set on the device, such as ciscoEnvMonTemperatureThreshold in this case, right? I thought that check_nwc_health parameters would be preferred to the internal thresholds of the device. So if I understand well this is not the case.

**Comment by lausser** [comment]
In this special case there are oids: The temperature value ciscoEnvMonTemperatureStatusValue The builtin ciscoEnvMonTemperatureThreshold The state ciscoEnvMonTemperatureState (a string „warning“, „critical“) It makes no sense to override the internal thresholds here. Even if you set criticalx to a much higher value than ciscoEnvMonTemperatureThreshold, the threshold in the perfdata would change, but ciscoEnvMonTemperatureState will still show critical if ciscoEnvMonTemperatureThreshold is reached. And i don’t want to ignore ciscoEnvMonTemperatureState. Gerhard Gesendet von  <https://go.microsoft.com/fwlink/?LinkId=550986> Mail für Windows 10 Von:  <mailto:notifications@github.com> Yannick Charton
 Gesendet:  Samstag, 7. Juli 2018 08:50
 An:  <mailto:check_nwc_health@noreply.github.com> lausser/check_nwc_health
 Cc:  <mailto:Gerhard.Lausser@consol.de> Gerhard Lausser ;  <mailto:comment@noreply.github.com> Comment
 Betreff:  Re: [lausser/check_nwc_health] warningx and criticalx not taken into account for mode hardware-health (#174)So, the "external" warning/critical (check_nwc_health warning/warningx/critical/criticalx parameters) are ignored when there is a threshold already set on the device, such as ciscoEnvMonTemperatureThreshold in this case, right? I thought that check_nwc_health parameters would be preferred to the internal thresholds of the device. So if I understand well this is not the case.

**Comment by Tontonitch** [comment]
Hello Gerhard,
Thanks for the information.
So, my question is answered, closing the issue.
BR,
Yannick
