### ISSUE TITLE
Hardware Health don't show CRITICAL PowerSupply

### ISSUE THREAD

**Issue by phil-or** [lausser/check_nwc_health#181]
First, thanks for the nwc_health checks, they are great!

At the moment we use two different versions. In one case, they show different check results.
We check the "hardware-health" from a Cisco WS-C3850-48P, where one power supply is broken.

check_nwc_health Version 6.4.1:
CRITICAL - powersupply 1015 (Switch 1 - Power Supply B, Shutdown) is shutdown | 'temp_1011'=25;60;;; 'temp_1012'=35;125;;; 'temp_1013'=34;125;;;

check_nwc_health Version 7.2.0.2:
OK - environmental hardware working fine | 'temp_1011'=25;60;;; 'temp_1012'=35;125;;; 'temp_1013'=34;125;;;

The newer version don't show the broken power supply, so now we are happy that we use two different nwc versions, but in the future we only use the newer version...
Can you explain why this error occurs?

**Comment by lausser** [comment]
Can you try this Version?
https://labs.consol.de/assets/downloads/nagios/check_nwc_health-7.3.0.1.tar.gz

**Comment by phil-or** [comment]
Works perfect!
Thank you!
