### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by H4cktz** [lausser/check_nwc_health#183]
Hi, I'm trying to install for first time at my nagios and I'm having this issue:

[root@nagios check_nwc_health]# make
Making install in plugins-scripts
make[1]: Entering directory `/root/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target `../GLPlugin/lib/Monitoring/GLPlugin/SNMP/MibsAndOids/INETADDRESSMIB.pm', needed by `check_nwc_health'.  Stop.
make[1]: Leaving directory `/root/check_nwc_health/plugins-scripts'
make: *** [install-recursive] Error 1
[root@nagios check_nwc_health]# cd GLPlugin; git checkout master; git pull; cd ..; git pull
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Already up to date.

[root@nagios]# cat /etc/issue
Red Hat Enterprise Linux Server release 6.7 (Santiago)

Please, I want this plugin so much. <3

**Comment by lausser** [comment]
Please run "git update" and "cd GLPlugin; git update" try again.

**Comment by H4cktz** [comment]
Hi Lausser,

I did it:
 Please run "git update" and "cd GLPlugin; git update" try again.

But:
 git: 'update' is not a git command. See 'git --help'.
The most similar command is
        update-ref

then I did it:
cd GLPlugin; git checkout master; git pull; cd ..; git pull

and:
[root@nagios plugins-scripts]# ./check_nwc_health --help
check_nwc_health $Revision: 7.3.0.2 $ [http://labs.consol.de/nagios/check_nwc_health]

It is WORKINGnow! Thank you so much <3

**Comment by Rohlik** [comment]
I have similar problem:

```
[root@devel check_nwc_health-7.10.0.4]# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for sh... /usr/bin/sh
checking for perl... /usr/bin/perl
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating plugins-scripts/Makefile
config.status: creating plugins-scripts/subst
                       --with-perl: /usr/bin/perl
                --with-nagios-user: nagios
               --with-nagios-group: nagios
              --disable-standalone:
```
```
[root@devel check_nwc_health-7.10.0.4]# make all
Making all in plugins-scripts
make[1]: Entering directory `/opt/check_nwc_health-7.10.0.4/plugins-scripts'
make[1]: *** No rule to make target `Classes/UPNP/AVM/FritzBox7390/Components/InterfaceSubsystem.pm', needed by `check_nwc_health'.  Stop.
make[1]: Leaving directory `/opt/check_nwc_health-7.10.0.4/plugins-scripts'
make: *** [all-recursive] Error 1
```
