### ISSUE TITLE
check_nwc_health timed out after 15 seconds

### ISSUE THREAD

**Issue by ekfarps** [lausser/check_nwc_health#185]
Hi,

we are running check_nwc_health $Revision: 7.3.0.2 on Ubuntu 14.04.5 LTS with Icinga 1.11.5.
The check is used to monitor our Brocade Switches and the Load Balancer pools on our BigIP F5.
Occasionally all of the check_nwc_health checks are failing with "check_nwc_health timed out after 15 seconds". In the event of the error trying to run the check manually also fails with the time out error.
The only solution to the problem is rebooting the whole Machine. This error occurs about from 2-3 time a week to 2-3 times a day with no apparant reason.

Icinga.log:
```
Warning: Unrecognized external command ->  MethodInvocationException;
External command error: Unknown or unsupported command
External command error: Malformed command
```
Things we checked:
Network connectivity is working normally
Disk Space and RAM usage are fine
CPU Load is fine

Things we tried unsuccessfully:
Restarting icinga Service
deleting all files in /tmp/check_nwc_health

Is there a way to enable debug messages or logging for check_nwc_health to see where exactly the time out occurs?

**Comment by lausser** [comment]
You can add 
-vvvvvvvvvvvv
and it will show you a lot of internal debug Information. There is also a --timeout.

But if a device becomes unresponsive just because it gets queried, then it's the problem of the device, there is not much you can do on the client side.

**Comment by ekfarps** [comment]
I don't think that 8 different devices suddenly become unresponsive and immediately responsive again after the monitoring server is rebooted.

**Comment by lausser** [comment]
Well, then i don't know what "suddenly" happened. I don't use Icinga.
