### ISSUE TITLE
interface-usage and warning/cricital values

### ISSUE THREAD

**Issue by jediblair** [lausser/check_nwc_health#189]
Just wondering if it is possible to customize the warning/cricital values on traffic usage  when using mode interface-usage?

I had a bit of a look at the code and looks like these are hard set at 80/90% of interface speed?

In my case it would be useful to be able to specify a specific traffic level to alarm on as we have circuits which while the port comes up at gigabit, the interface is shaped to a different speed.

**Comment by lausser** [comment]
check_nwc_health --hostname 1.1.1.1 --timeout 60 --community geheim --mode interface-usage --name '^TenGigabitEthernet.*\/1/2' --regexp
now you get only 2 interfaces:

OK - interface TenGigabitEthernet1/1/2 usage is in:0.00% (0.00bit/s) out:0.00% (0.00bit/s) (down)
interface TenGigabitEthernet2/1/2 usage is in:0.00% (0.00bit/s) out:0.00% (0.00bit/s) (down) | 'TenGigabitEthernet1/1/2_usage_in'=0%;80;90;0;100 'TenGigabitEthernet1/1/2_usage_out'=0%;80;90;0;100 'TenGigabitEthernet1/1/2_traffic_in'=0;0;0;0;0 'TenGigabitEthernet1/1/2_traffic_out'=0;0;0;0;0 'TenGigabitEthernet2/1/2_usage_in'=0%;80;90;0;100 'TenGigabitEthernet2/1/2_usage_out'=0%;80;90;0;100 'TenGigabitEthernet2/1/2_traffic_in'=0;0;0;0;0 'TenGigabitEthernet2/1/2_traffic_out'=0;0;0;0;0

They are down, but thats not relevant for this example.  You can use --warning/critical to set global thresholds:
check_nwc_health --hostname 1.1.1.1 --timeout 60 --community geheim --mode interface-usage --name '^TenGigabitEthernet.*\/1/2' --regexp
 --warning 40 --critical 99
OK - interface TenGigabitEthernet1/1/2 usage is in:0.00% (0.00bit/s) out:0.00% (0.00bit/s) (down)
interface TenGigabitEthernet2/1/2 usage is in:0.00% (0.00bit/s) out:0.00% (0.00bit/s) (down) | 'TenGigabitEthernet1/1/2_usage_in'=0%;40;99;0;100 'TenGigabitEthernet1/1/2_usage_out'=0%;40;99;0;100 'TenGigabitEthernet1/1/2_traffic_in'=0;40;99;0;0 'TenGigabitEthernet1/1/2_traffic_out'=0;40;99;0;0 'TenGigabitEthernet2/1/2_usage_in'=0%;40;99;0;100 'TenGigabitEthernet2/1/2_usage_out'=0%;40;99;0;100 'TenGigabitEthernet2/1/2_traffic_in'=0;40;99;0;0 'TenGigabitEthernet2/1/2_traffic_out'=0;40;99;0;0

But you can also use --warningx/criticalx to set individual thresholds for certain interfaces. Just pick the right perfdata label:

check_nwc_health --hostname 1.1.1.1 --timeout 60 --community geheim --mode interface-usage --name '^TenGigabitEthernet.*\/1/2' --regexp
 --warning 40 --critical 99 --warningx 'TenGigabitEthernet2/1/2_usage_in'=70
OK - interface TenGigabitEthernet1/1/2 usage is in:0.00% (0.00bit/s) out:0.00% (0.00bit/s) (down)
interface TenGigabitEthernet2/1/2 usage is in:0.00% (0.00bit/s) out:0.00% (0.00bit/s) (down) | 'TenGigabitEthernet1/1/2_usage_in'=0%;40;99;0;100 'TenGigabitEthernet1/1/2_usage_out'=0%;40;99;0;100 'TenGigabitEthernet1/1/2_traffic_in'=0;40;99;0;0 'TenGigabitEthernet1/1/2_traffic_out'=0;40;99;0;0 'TenGigabitEthernet2/1/2_usage_in'=0%;70;99;0;100 'TenGigabitEthernet2/1/2_usage_out'=0%;40;99;0;100 'TenGigabitEthernet2/1/2_traffic_in'=0;40;99;0;0 'TenGigabitEthernet2/1/2_traffic_out'=0;40;99;0;0
