### ISSUE TITLE
count-connections dosn't work with 7.7 anymore for cisco asa

### ISSUE THREAD

**Issue by ClemensBW** [lausser/check_nwc_health#210]
Hello,

the count-connections don't work with V 7.7 anymore at cisco asa, with V7.4.1.2 (not test later) it works fine: "Mode count-connections is not implemented for this type of device"

Uptime, hardware and all other works without any problem.

**Comment by lausser** [comment]
Can you please run
check_nwc_health .... --mode walk | bash
and mail me the resulting file (/tmp/...something with snmpwalk...) to gerhard.lausser@consol.de?
Gerhard

**Comment by ClemensBW** [comment]
fixed with V 7.9 - thank you!
