### ISSUE TITLE
--mode interface-health produces "Use of uninitialized value in string eq" with --servertype linuxlocal

### ISSUE THREAD

**Issue by K0nne** [lausser/check_nwc_health#228]
Hello lausser,

when I run the following command, I get an "use of uninitialized value" error:

`/usr/lib64/nagios/plugins/check_nwc_health -H localhost --mode interface-status --servertype linuxlocal`

**Use of uninitialized value in string eq at ./check_nwc_health line 59150.**
OK - bond0 is up/up, interface bond0 usage is in:0.53% (5541779.24bit/s) out:0.59% (6192775.28bit/s), interface bond0 errors in:0.00/s out:0.00/s , interface bond0 discards in:0.00/s out:0.00/s , interface bond0 broadcast in:0.00% out:0.00% , bonding_masters is 0/0, em1 is down/down, em2 is down/down, em3 is up/up, interface em3 usage is in:0.53% (5541625.80bit/s) out:0.59% (6192731.33bit/s), interface em3 errors in:0.00/s out:0.00/s , interface em3 discards in:0.00/s out:0.00/s , interface em3 broadcast in:0.00% out:0.00% , em4 is up/up, interface em4 usage is in:0.00% (37.75bit/s) out:0.00% (0.00bit/s), interface em4 errors in:0.00/s out:0.00/s , interface em4 discards in:0.00/s out:0.00/s , interface em4 broadcast in:0.00% out:0.00% , lo is up/up, interface lo usage is in:0.00% (2595311.46bit/s) out:0.00% (2595311.46bit/s), interface lo errors in:0.00/s out:0.00/s , interface lo discards in:0.00/s out:0.00/s , interface lo broadcast in:0.00% out:0.00%  | 'bond0_usage_in'=0.53%;80;90;0;100 'bond0_usage_out'=0.59%;80;90;0;100 'bond0_traffic_in'=5541779.24;838860800;943718400;0;1048576000 'bond0_traffic_out'=6192775.28;838860800;943718400;0;1048576000 'bond0_errors_in'=0;1;10;; 'bond0_errors_out'=0;1;10;; 'bond0_discards_in'=0;1;10;; 'bond0_discards_out'=0;1;10;; 'bond0_broadcast_in'=0%;10;20;0;100 'bond0_broadcast_out'=0%;10;20;0;100 'em3_usage_in'=0.53%;80;90;0;100 'em3_usage_out'=0.59%;80;90;0;100 'em3_traffic_in'=5541625.80;838860800;943718400;0;1048576000 'em3_traffic_out'=6192731.33;838860800;943718400;0;1048576000 'em3_errors_in'=0;1;10;; 'em3_errors_out'=0;1;10;; 'em3_discards_in'=0;1;10;; 'em3_discards_out'=0;1;10;; 'em3_broadcast_in'=0%;10;20;0;100 'em3_broadcast_out'=0%;10;20;0;100 'em4_usage_in'=0.00%;80;90;0;100 'em4_usage_out'=0%;80;90;0;100 'em4_traffic_in'=37.75;838860800;943718400;0;1048576000 'em4_traffic_out'=0;838860800;943718400;0;1048576000 'em4_errors_in'=0;1;10;; 'em4_errors_out'=0;1;10;; 'em4_discards_in'=0;1;10;; 'em4_discards_out'=0;1;10;; 'em4_broadcast_in'=0%;10;20;0;100 'em4_broadcast_out'=0%;10;20;0;100 'lo_usage_in'=0%;80;90;0;100 'lo_usage_out'=0%;80;90;0;100 'lo_traffic_in'=2595311.46;0;0;0;0 'lo_traffic_out'=2595311.46;0;0;0;0 'lo_errors_in'=0;1;10;; 'lo_errors_out'=0;1;10;; 'lo_discards_in'=0;1;10;; 'lo_discards_out'=0;1;10;; 'lo_broadcast_in'=0%;10;20;0;100 'lo_broadcast_out'=0%;10;20;0;100

The error does not appear when I use the following additional arguments:

`--regexp true --name "bond0|lo|em"`

This is the affected code:

```
if ($tmpif->{ifOperStatus} eq 'unknown') {
    $tmpif->{ifOperStatus} = $tmpif->{ifCarrier} ? 'up' : 'down';
}
```

Thanks and servus

**Comment by lausser** [comment]
Can you run it with "-vv" and withous "--name..." please. Then post the output.

**Comment by K0nne** [comment]
Here is the output:

`./check_nwc_health -H localhost --mode interface-health --servertype linuxlocal -vv
Use of uninitialized value in string eq at ./check_nwc_health line 59150.
[INTERFACESUBSYSTEM]
info: checking interfaces
[INTERFACE]
broadcastInPercent: 0
broadcastOutPercent: 0
delta_ifInBits: 281947424
delta_ifInBroadcastPkts: 0
delta_ifInDiscards: 0
delta_ifInErrors: 0
delta_ifInMulticastPkts: 0
delta_ifInOctets: 35243428
delta_ifInUcastPkts: 0
delta_ifOutBits: 284509824
delta_ifOutBroadcastPkts: 0
delta_ifOutDiscards: 0
delta_ifOutErrors: 0
delta_ifOutMulticastPkts: 0
delta_ifOutOctets: 35563728
delta_ifOutUcastPkts: 0
delta_timestamp: 52
ifAdminStatus: up
ifCarrier: 1
ifDescr: bond0
ifInBroadcastPkts: 0
ifInBroadcastPkts_per_sec: 0
ifInDiscards: 0
ifInDiscards_per_sec: 0
ifInErrors: 0
ifInErrors_per_sec: 0
ifInMulticastPkts: 0
ifInMulticastPkts_per_sec: 0
ifInOctets: 835051972971
ifInOctets_per_sec: 677758.230769231
ifInUcastPkts: 0
ifInUcastPkts_per_sec: 0
ifIndex: bond0
ifOperStatus: up
ifOutBroadcastPkts: 0
ifOutBroadcastPkts_per_sec: 0
ifOutDiscards: 0
ifOutDiscards_per_sec: 0
ifOutErrors: 0
ifOutErrors_per_sec: 0
ifOutMulticastPkts: 0
ifOutMulticastPkts_per_sec: 0
ifOutOctets: 1487398555278
ifOutOctets_per_sec: 683917.846153846
ifOutUcastPkts: 0
ifOutUcastPkts_per_sec: 0
ifSpeed: 1048576000
inputDiscardRate: 0
inputErrorRate: 0
inputRate: 5422065.84615385
inputUtilization: 0.517088493934044
maxInputRate: 1048576000
maxOutputRate: 1048576000
outputDiscardRate: 0
outputErrorRate: 0
outputRate: 5471342.76923077
outputUtilization: 0.521787907527043
sysMaxSpeed: 1000
info: interface bond0 broadcast in:0.00% out:0.00%

[VIRT]
ifAdminStatus: 0
ifCarrier: 0
ifDescr: bonding_masters
ifInDiscards: 0
ifInErrors: 0
ifInOctets: 0
ifInUcastPkts: 0
ifIndex: bonding_masters
ifOperStatus: 0
ifOutDiscards: 0
ifOutErrors: 0
ifOutOctets: 0
ifOutUcastPkts: 0
ifSpeed: 0
sysMaxSpeed: 1000
info: bonding_masters is 0/0

[VIRT]
ifAdminStatus: down
ifCarrier: 0
ifDescr: em1
ifInDiscards: 0
ifInErrors: 0
ifInOctets: 0
ifInUcastPkts: 0
ifIndex: em1
ifOperStatus: down
ifOutDiscards: 0
ifOutErrors: 0
ifOutOctets: 0
ifOutUcastPkts: 0
ifSpeed: 0
sysMaxSpeed: 1000
info: em1 is down/down

[VIRT]
ifAdminStatus: down
ifCarrier: 0
ifDescr: em2
ifInDiscards: 0
ifInErrors: 0
ifInOctets: 0
ifInUcastPkts: 0
ifIndex: em2
ifOperStatus: down
ifOutDiscards: 0
ifOutErrors: 0
ifOutOctets: 0
ifOutUcastPkts: 0
ifSpeed: 0
sysMaxSpeed: 1000
info: em2 is down/down

[INTERFACE]
broadcastInPercent: 0
broadcastOutPercent: 0
delta_ifInBits: 282180608
delta_ifInBroadcastPkts: 0
delta_ifInDiscards: 0
delta_ifInErrors: 0
delta_ifInMulticastPkts: 0
delta_ifInOctets: 35272576
delta_ifInUcastPkts: 0
delta_ifOutBits: 284550128
delta_ifOutBroadcastPkts: 0
delta_ifOutDiscards: 0
delta_ifOutErrors: 0
delta_ifOutMulticastPkts: 0
delta_ifOutOctets: 35568766
delta_ifOutUcastPkts: 0
delta_timestamp: 52
ifAdminStatus: up
ifCarrier: 1
ifDescr: em3
ifInBroadcastPkts: 0
ifInBroadcastPkts_per_sec: 0
ifInDiscards: 0
ifInDiscards_per_sec: 0
ifInErrors: 0
ifInErrors_per_sec: 0
ifInMulticastPkts: 0
ifInMulticastPkts_per_sec: 0
ifInOctets: 835044769101
ifInOctets_per_sec: 678318.769230769
ifInUcastPkts: 0
ifInUcastPkts_per_sec: 0
ifIndex: em3
ifOperStatus: up
ifOutBroadcastPkts: 0
ifOutBroadcastPkts_per_sec: 0
ifOutDiscards: 0
ifOutDiscards_per_sec: 0
ifOutErrors: 0
ifOutErrors_per_sec: 0
ifOutMulticastPkts: 0
ifOutMulticastPkts_per_sec: 0
ifOutOctets: 1487398560498
ifOutOctets_per_sec: 684014.730769231
ifOutUcastPkts: 0
ifOutUcastPkts_per_sec: 0
ifSpeed: 1048576000
inputDiscardRate: 0
inputErrorRate: 0
inputRate: 5426550.15384615
inputUtilization: 0.517516150841346
maxInputRate: 1048576000
maxOutputRate: 1048576000
outputDiscardRate: 0
outputErrorRate: 0
outputRate: 5472117.84615385
outputUtilization: 0.521861824622521
sysMaxSpeed: 1000
info: interface em3 broadcast in:0.00% out:0.00%

[INTERFACE]
broadcastInPercent: 0
broadcastOutPercent: 0
delta_ifInBits: 3360
delta_ifInBroadcastPkts: 0
delta_ifInDiscards: 0
delta_ifInErrors: 0
delta_ifInMulticastPkts: 0
delta_ifInOctets: 420
delta_ifInUcastPkts: 0
delta_ifOutBits: 0
delta_ifOutBroadcastPkts: 0
delta_ifOutDiscards: 0
delta_ifOutErrors: 0
delta_ifOutMulticastPkts: 0
delta_ifOutOctets: 0
delta_ifOutUcastPkts: 0
delta_timestamp: 52
ifAdminStatus: up
ifCarrier: 1
ifDescr: em4
ifInBroadcastPkts: 0
ifInBroadcastPkts_per_sec: 0
ifInDiscards: 0
ifInDiscards_per_sec: 0
ifInErrors: 0
ifInErrors_per_sec: 0
ifInMulticastPkts: 0
ifInMulticastPkts_per_sec: 0
ifInOctets: 7233438
ifInOctets_per_sec: 8.07692307692308
ifInUcastPkts: 0
ifInUcastPkts_per_sec: 0
ifIndex: em4
ifOperStatus: up
ifOutBroadcastPkts: 0
ifOutBroadcastPkts_per_sec: 0
ifOutDiscards: 0
ifOutDiscards_per_sec: 0
ifOutErrors: 0
ifOutErrors_per_sec: 0
ifOutMulticastPkts: 0
ifOutMulticastPkts_per_sec: 0
ifOutOctets: 0
ifOutOctets_per_sec: 0
ifOutUcastPkts: 0
ifOutUcastPkts_per_sec: 0
ifSpeed: 1048576000
inputDiscardRate: 0
inputErrorRate: 0
inputRate: 64.6153846153846
inputUtilization: 6.16220327524038e-06
maxInputRate: 1048576000
maxOutputRate: 1048576000
outputDiscardRate: 0
outputErrorRate: 0
outputRate: 0
outputUtilization: 0
sysMaxSpeed: 1000
info: interface em4 broadcast in:0.00% out:0.00%

[VIRT]
broadcastInPercent: 0
broadcastOutPercent: 0
delta_ifInBits: 138141840
delta_ifInBroadcastPkts: 0
delta_ifInDiscards: 0
delta_ifInErrors: 0
delta_ifInMulticastPkts: 0
delta_ifInOctets: 17267730
delta_ifInUcastPkts: 0
delta_ifOutBits: 138141840
delta_ifOutBroadcastPkts: 0
delta_ifOutDiscards: 0
delta_ifOutErrors: 0
delta_ifOutMulticastPkts: 0
delta_ifOutOctets: 17267730
delta_ifOutUcastPkts: 0
delta_timestamp: 52
ifAdminStatus: up
ifCarrier: 1
ifDescr: lo
ifInBroadcastPkts: 0
ifInBroadcastPkts_per_sec: 0
ifInDiscards: 0
ifInDiscards_per_sec: 0
ifInErrors: 0
ifInErrors_per_sec: 0
ifInMulticastPkts: 0
ifInMulticastPkts_per_sec: 0
ifInOctets: 331527364572
ifInOctets_per_sec: 332071.730769231
ifInUcastPkts: 0
ifInUcastPkts_per_sec: 0
ifIndex: lo
ifOperStatus: up
ifOutBroadcastPkts: 0
ifOutBroadcastPkts_per_sec: 0
ifOutDiscards: 0
ifOutDiscards_per_sec: 0
ifOutErrors: 0
ifOutErrors_per_sec: 0
ifOutMulticastPkts: 0
ifOutMulticastPkts_per_sec: 0
ifOutOctets: 331527364572
ifOutOctets_per_sec: 332071.730769231
ifOutUcastPkts: 0
ifOutUcastPkts_per_sec: 0
ifSpeed: 0
inputDiscardRate: 0
inputErrorRate: 0
inputRate: 2656573.84615385
inputUtilization: 0
maxInputRate: 0
maxOutputRate: 0
outputDiscardRate: 0
outputErrorRate: 0
outputRate: 2656573.84615385
outputUtilization: 0
sysMaxSpeed: 1000
info: interface lo broadcast in:0.00% out:0.00%


CRITICAL - em1 is admin down, em2 is admin down, bond0 is up/up, interface bond0 usage is in:0.52% (5422065.85bit/s) out:0.52% (5471342.77bit/s), interface bond0 errors in:0.00/s out:0.00/s , interface bond0 discards in:0.00/s out:0.00/s , interface bond0 broadcast in:0.00% out:0.00% , bonding_masters is 0/0, em1 is down/down, em2 is down/down, em3 is up/up, interface em3 usage is in:0.52% (5426550.15bit/s) out:0.52% (5472117.85bit/s), interface em3 errors in:0.00/s out:0.00/s , interface em3 discards in:0.00/s out:0.00/s , interface em3 broadcast in:0.00% out:0.00% , em4 is up/up, interface em4 usage is in:0.00% (64.62bit/s) out:0.00% (0.00bit/s), interface em4 errors in:0.00/s out:0.00/s , interface em4 discards in:0.00/s out:0.00/s , interface em4 broadcast in:0.00% out:0.00% , lo is up/up, interface lo usage is in:0.00% (2656573.85bit/s) out:0.00% (2656573.85bit/s), interface lo errors in:0.00/s out:0.00/s , interface lo discards in:0.00/s out:0.00/s , interface lo broadcast in:0.00% out:0.00%
checking interfaces
bond0 is up/up
interface bond0 usage is in:0.52% (5422065.85bit/s) out:0.52% (5471342.77bit/s)
interface bond0 errors in:0.00/s out:0.00/s
interface bond0 discards in:0.00/s out:0.00/s
interface bond0 broadcast in:0.00% out:0.00%
bonding_masters is 0/0
em1 is down/down
em2 is down/down
em3 is up/up
interface em3 usage is in:0.52% (5426550.15bit/s) out:0.52% (5472117.85bit/s)
interface em3 errors in:0.00/s out:0.00/s
interface em3 discards in:0.00/s out:0.00/s
interface em3 broadcast in:0.00% out:0.00%
em4 is up/up
interface em4 usage is in:0.00% (64.62bit/s) out:0.00% (0.00bit/s)
interface em4 errors in:0.00/s out:0.00/s
interface em4 discards in:0.00/s out:0.00/s
interface em4 broadcast in:0.00% out:0.00%
lo is up/up
interface lo usage is in:0.00% (2656573.85bit/s) out:0.00% (2656573.85bit/s)
interface lo errors in:0.00/s out:0.00/s
interface lo discards in:0.00/s out:0.00/s
interface lo broadcast in:0.00% out:0.00%  | 'bond0_usage_in'=0.52%;80;90;0;100 'bond0_usage_out'=0.52%;80;90;0;100 'bond0_traffic_in'=5422065.85;838860800;943718400;0;1048576000 'bond0_traffic_out'=5471342.77;838860800;943718400;0;1048576000 'bond0_errors_in'=0;1;10;; 'bond0_errors_out'=0;1;10;; 'bond0_discards_in'=0;1;10;; 'bond0_discards_out'=0;1;10;; 'bond0_broadcast_in'=0%;10;20;0;100 'bond0_broadcast_out'=0%;10;20;0;100 'em3_usage_in'=0.52%;80;90;0;100 'em3_usage_out'=0.52%;80;90;0;100 'em3_traffic_in'=5426550.15;838860800;943718400;0;1048576000 'em3_traffic_out'=5472117.85;838860800;943718400;0;1048576000 'em3_errors_in'=0;1;10;; 'em3_errors_out'=0;1;10;; 'em3_discards_in'=0;1;10;; 'em3_discards_out'=0;1;10;; 'em3_broadcast_in'=0%;10;20;0;100 'em3_broadcast_out'=0%;10;20;0;100 'em4_usage_in'=0.00%;80;90;0;100 'em4_usage_out'=0%;80;90;0;100 'em4_traffic_in'=64.62;838860800;943718400;0;1048576000 'em4_traffic_out'=0;838860800;943718400;0;1048576000 'em4_errors_in'=0;1;10;; 'em4_errors_out'=0;1;10;; 'em4_discards_in'=0;1;10;; 'em4_discards_out'=0;1;10;; 'em4_broadcast_in'=0%;10;20;0;100 'em4_broadcast_out'=0%;10;20;0;100 'lo_usage_in'=0%;80;90;0;100 'lo_usage_out'=0%;80;90;0;100 'lo_traffic_in'=2656573.85;0;0;0;0 'lo_traffic_out'=2656573.85;0;0;0;0 'lo_errors_in'=0;1;10;; 'lo_errors_out'=0;1;10;; 'lo_discards_in'=0;1;10;; 'lo_discards_out'=0;1;10;; 'lo_broadcast_in'=0%;10;20;0;100 'lo_broadcast_out'=0%;10;20;0;100`

Maybe this this is the problem:

ifOperStatus: 0

**Comment by K0nne** [comment]
Thank you very much!
