### ISSUE TITLE
how to check interface-status only for administratively UP interfaces?

### ISSUE THREAD

**Issue by OG2K** [lausser/check_nwc_health#243]
Dears,

I do understand, that I could determine which interfaces to check via name argument.
But how do I specify execute interface-status checks only for administratively UP interfaces?
I do not want to mitigate or negate or whatever solutions might be proposed.
I would like to specify all interfaces to check which are not administratively down.

Thanks for your time,
/A

**Comment by OG2K** [comment]
1)

When only specified interfaces are monitored, there will be no new additional check performed, when new interface will be configured.
When check is configured to check only administratively UP interfaces, after device re-configuration, additional check will be performed, because additional interface will be administratively UP.

2)

I have configured check_nwc_health via apply rules in icinga and have about 10 devices to monitor with different amount of interfaces (from 8 to 2x48) and I am not alone. What I do now? I split checks for each device separately, specifying interfaces to check manually. :( Knowing, that when new interface come up, I need to come back and adjust --name argument.

Thank you for understanding,
/A

**Comment by lausser** [comment]
`--name _adminup_`

**Comment by OG2K** [comment]
Dear Gerhard,
Many thanks for help. Value for --name _adminup_ was not found in any documentation.
Works, as expected. :)
BR /A
