### ISSUE TITLE
Cisco Firepower Uptime Check 

### ISSUE THREAD

**Issue by bschymanski** [lausser/check_nwc_health#282]
Hallo,

seit einem update der ASA Software einer Cisco Firepower 2130 funktioniert der uptime Check nicht mehr.
Per snmpwalk werden die korrekten Daten angezeigt.
Ich habe auch schon diverse andere --servertype systeme ausprobiert, es ändert sich nichts.

[username@monitoringserver ~]$ snmpwalk -v3 -u snmpuser -l authpriv -a SHA -A authprivpw -x AES128 -X authprivpw 192.168.1.1
SNMPv2-MIB::sysDescr.0 = STRING: Cisco Adaptive Security Appliance Version 9.14(2)13
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.2406
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (8967100) 1 day, 0:54:31.00
SNMPv2-MIB::sysContact.0 = STRING: contact@mail
SNMPv2-MIB::sysName.0 = STRING: cust-loc-asa-1

[username@monitoringserver ~]$ snmpwalk -v3 -u snmpuser -l authpriv -a SHA -A authprivpw -x AES128 -X authprivpw 192.168.10.10
SNMPv2-MIB::sysDescr.0 = STRING: Cisco FirePOWER FPR-2130 Security Appliance, System Version 2.8(1.144)
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.2406
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (8998146) 1 day, 0:59:41.46
SNMPv2-MIB::sysContact.0 = STRING: ''
SNMPv2-MIB::sysName.0 = STRING: firepower-2130.local.domain

[username@monitoringserver ~]$ /usr/lib64/nagios/plugins/check_nwc_health --protocol 3 --username snmpuser --authpassword authprivpw --authprotocol sha --privpassword authprivpw --privprotocol aes --hostname 192.168.10.10 --mode uptime
CRITICAL - device is up since 0h 2m 50s, Cisco FirePOWER FPR-2130 Security Appliance, System Version 2.8(1.144) | 'uptime'=3;15:;5:;;

[username@monitoringserver ~]$ /usr/lib64/nagios/plugins/check_nwc_health --protocol 3 --username snmpuser --authpassword authprivpw --authprotocol sha --privpassword authprivpw --privprotocol aes --hostname 192.168.1.1 --mode uptime
CRITICAL - device is up since 0h 4m 11s, Cisco Adaptive Security Appliance Version 9.14(2)13 | 'uptime'=4;15:;5:;;
[username@monitoringserver ~]$

**Comment by lausser** [comment]
Das dürfte sich in Kürze beruhigen. 
'uptime'=4;15:;5:;; -> Uptime unter 5 Minuten = Alarm

**Comment by bschymanski** [comment]
Moin, - nope, das ist ja das problem. Die Uptimewerte steigen nie über 3-4 minuten und gehen dann wieder auf null. Dafür hab ich die tatsächlichen werte über den snmpwalk mitgeliefert
