### ISSUE TITLE
Wrong include causes problem in Classes/IFMIB/Component/InterfaceSubsystem.pm

### ISSUE THREAD

**Issue by ironiq** [lausser/check_nwc_health#294]
In commit 8396338 the cache file handling method was changed from Data::Dumper to JSON::XS. The problem is that the file in $subject includes only the "JSON" module and not the JSON::XS. Changing the line to "use JSON::XS" at least informs the user about the missing dependency if the given module is not installed. Otherwise the user will be informed that the interface-usage (and other modes in Classes::IFMIB::Component::InterfaceSubsytem) is not implemented ("UNKNOWN - Mode interface-usage is not implemented for this type of device").

**Comment by einhander** [comment]
@ironiq thank you! I've spent a whole day to figure that's wrong on my server, because in dev environment  it works just fine.

**Comment by ironiq** [comment]
issue fixed with PR #299
