### ISSUE TITLE
Message String: Adaptive Server connection failed

### ISSUE THREAD

**Issue by proebstle** [lausser/check_nwc_health#313]
Hi,

running on Debian GNU/Linux 10 (buster)
since last update apt-get update and upgrade the follow error on "old" SQL Servers. New SQL Servers without problems....

------------------------------------------------------------------------------------------------------------------------
/omd/sites/xxx/lib/monitoring-plugins/check_mssql_health --offlineok --notemp --multiline --server 'KK-SQL-02' --username 'sa' --password xxx --mode cpu-busy

CRITICAL - DBI connect(';server=KK-SQL-02;encryptPassword=1','sa',...) failed: OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (34)
Server KK-SQL-02, database
Message String: Adaptive Server connection failed
OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (34)
Server KK-SQL-02, database
Message String: Adaptive Server connection failed
 at /omd/sites/xxx/lib/monitoring-plugins/check_mssql_health line 6718.
------------------------------------------------------------------------------------------------------------------------

Any idea?

**Comment by lausser** [comment]
I have no idea. Maybe the old servers do not use encrypted communication and the pre-upgrade-freetds libraries ignored the encryptPassword=1 but now enforce encryption?

**Comment by proebstle** [comment]
After new update issue solved...

The following packages will be upgraded:
  libapache2-mod-php7.3 php7.3 php7.3-cgi php7.3-cli php7.3-common php7.3-gd php7.3-json php7.3-mbstring php7.3-opcache php7.3-readline php7.3-sqlite3 php7.3-xml
12 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by lausser** [comment]
What??!?! Updated PHP-packages solved a MS SQL issue with a Perl plugin? Strange, but i wish every issue could be solved so easily. :-)
