### ISSUE TITLE
check_nwc_health performance issues.

### ISSUE THREAD

**Issue by yuvarajan1989k** [lausser/check_nwc_health#315]
Hi,

i m using check_nwc_health for montioring bandwidth of network devices which is totally 300 devices. whenever the check_nwc_health script run, the cpu usage goes very high. did any one face these kind of issues?

**Comment by lausser** [comment]
If you use OMD (https://omd.consol.de/docs/omd/), the setup of check_nwc_halth is optimized to profitfrom separation of the plugin and the numerous MIB module files. Also OMD has a worker process which runs plugins (written in Perl) in an embedded Perl interpretet. This way there is no startup of plugins necessary and the initial interpretation of the code is also done only once (or when a plugin has changes)
