### ISSUE TITLE
hardware-health not working anymore for latest PANOS (seen with PA-440, PA-850)

### ISSUE THREAD

**Issue by wdetter** [lausser/check_nwc_health#316]
Hi, 

seems like hardware-health doesn't work anymore since the latest PANOS-Upgrades. For example, seen with:
a) PA-850, PANOS 10.1.9
b) PA-440, PANOS, 10.2.4

`check_nwc_health --hostname 10.10.1.1 --mode hardware-health --community whatever -t 600 -vvv`

[TEMPERATURE_2]
entPhySensorEntityName: CPU die Temperature
entPhySensorOperStatus: ok
entPhySensorPrecision: 0
entPhySensorScale: units
entPhySensorType: celsius
entPhySensorUnitsDisplay: (C)
entPhySensorValue: 54
entPhySensorValueTimeStamp: 0
entPhySensorValueUpdateRate: 0
entPhysicalIndex: 2
info: celsius sensor CPU die Temperature reports 54(C)

[DISKSUBSYSTEM]
info: checking storages
[STORAGE_1040]
hrStorageAllocationUnits: 1024
hrStorageDescr: Slot-1 Management Config Partition
hrStorageIndex: 1040
hrStorageSize: 21381708
hrStorageType: hrStorageFixedDisk
hrStorageUsed: 7193340
name: Slot-1 Management Config Partition
special: 0
info: storage 1040 (Slot-1 Management Config Partition) has 66.36% free space left

[STORAGE_1041]
hrStorageAllocationUnits: 1024
hrStorageDescr: Slot-1 Management Log Partition
hrStorageIndex: 1041
hrStorageSize: 1007512
hrStorageType: hrStorageFixedDisk
hrStorageUsed: 509240
name: Slot-1 Management Log Partition
special: 0
info: storage 1041 (Slot-1 Management Log Partition) has 49.46% free space left

[STORAGE_1042]
hrStorageAllocationUnits: 1024
hrStorageDescr: Slot-1 Management Root Partition
hrStorageIndex: 1042
hrStorageSize: 11122220
hrStorageType: hrStorageFixedDisk
hrStorageUsed: 4739328
name: Slot-1 Management Root Partition
special: 0
info: storage 1042 (Slot-1 Management Root Partition) has 57.39% free space left

[DEVICESUBSYSTEM]
info: checking devices
[HRDEVICEPROCESSOR_1]
hrDeviceDescr: Slot-1 Management Processor
hrDeviceID: 0.0
hrDeviceIndex: 1
hrDeviceStatus: running
hrDeviceType: hrDeviceProcessor
info: hrDeviceProcessor (Slot-1 Management Processor) has status running

[HRDEVICEPROCESSOR_2]
hrDeviceDescr: Slot-1 Data Processor
hrDeviceID: 0.0
hrDeviceIndex: 2
hrDeviceStatus: down
hrDeviceType: hrDeviceProcessor
info: hrDeviceProcessor (Slot-1 Data Processor) has status down

CRITICAL - hrDeviceProcessor (Slot-1 Data Processor) has status down, environmental hardware working fine, storage 1040 (Slot-1 Management Config Partition) has 66.36% free space left, storage 1041 (Slot-1 Management Log Partition) has 49.46% free space left, storage 1042 (Slot-1 Management Root Partition) has 57.39% free space left, hrDeviceProcessor (Slot-1 Management Processor) has status running
celsius sensor CPU die Temperature reports 54(C)
checking storages
storage 1040 (Slot-1 Management Config Partition) has 66.36% free space left
storage 1041 (Slot-1 Management Log Partition) has 49.46% free space left
storage 1042 (Slot-1 Management Root Partition) has 57.39% free space left
checking devices
hrDeviceProcessor (Slot-1 Management Processor) has status running
hrDeviceProcessor (Slot-1 Data Processor) has status down | 'temp_CPU die Temperature'=54;;;; 'Slot-1 Management Config Partition_free_pct'=66.36%;10:;5:;0;100 'Slot-1 Management Log Partition_free_pct'=49.46%;10:;5:;0;100 'Slot-1 Management Root Partition_free_pct'=57.39%;10:;5:;0;100

Seems like something has changed with the Palo Alto MIBS/SNMP -  but I don't find an exact match in the changelogs:
* https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-release-notes/pan-os-10-2-4-known-and-addressed-issues/pan-os-10-2-4-addressed-issues
* https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-release-notes/pan-os-10-1-9-known-and-addressed-issues/pan-os-10-1-9-addressed-issues

It could be releated to the Palo Alto Networks fix PAN-189027 but this is just a guess. 
Please let me know if you need more information. 

Thanks,
Werner

**Comment by gavellan** [comment]
Same issue.

**Comment by SereinCedrix** [comment]
Same Issue on PA-3430

**Comment by lausser** [comment]
I have a customer who says that this is a known issue at palo alto and that it will get fixed with a future os update. Nothing which can be done in the plugin.
Meanwhile they added --blacklist HRDEVICEPROCESSOR_2
