### ISSUE TITLE
No perfdata generated with mode "interface-nat-rejects"

### ISSUE THREAD

**Issue by Tontonitch** [lausser/check_nwc_health#320]
Hello,
It would be great that the mode "interface-nat-rejects" also returns perfdata, to have a history of the rejected packet rate.
```
OK - 0.00% of all other packets have been dropped/rejected, 0.00% of all icmp packets have been dropped/rejected, 0.00% of all udp packets have been dropped/rejected, 0.00% of all tcp packets have been dropped/rejected
r
```
Currently, as it is missing, I switched to multiple check_snmp services to have the stats and history, but it is of course not optimal.
BR,
Yannick

**Comment by lausser** [comment]
It's added, version 11.2.3
And should be in tomorrow's OMD.
