### ISSUE TITLE
Update of F5 broke check_nwc_health

### ISSUE THREAD

**Issue by slalomsk8er** [lausser/check_nwc_health#327]
Today's update broke at least the pool checks.

```
 $ ... '--mode' 'list-pools' -vvv
[LTMSUBSYSTEM4]
sysPlatformInfoMarketingName: BIG-IP i5600
sysProductVersion: 4
info: checking ltm pools

UNKNOWN - no pools
checking ltm pools
```

Change was: Security Upgrade von Version 16.1.4.1 auf 17.1.1.1 der F5 Appliances

**Comment by xtra-be** [comment]
i tried this and it's not working
i checked the commit it was missing in my release version
but even when manualy applying it does not work

[LTMSUBSYSTEM4]
sysPlatformInfoMarketingName: BIG-IP vCMP Guest
sysProductVersion: 4
info: checking ltm pools

UNKNOWN - no pools
checking ltm pools

**Comment by lausser** [comment]
Please run
check_nwc_health .... --mode bulkwalk
which shows you two snmpwalk commands. Run them and mail me the resulting file, then i can simulate your device.
