### ISSUE TITLE
Interfaces missing when querying Cisco Catalyst 2960 switches 

### ISSUE THREAD

**Issue by Finn10111** [lausser/check_nwc_health#34]
I am using check_nwc_health (currently version 3.4.3) and there seems to be a interface-related problem. When querying Cisco switches for interface-related data (tested with modes interface-usage, interface-status, list-interfaces, list-interfaces-detail) not all interfaces are shown. 

I have seen this issue on different switches, e.g. C2960S and C2960X. One switch is a stacked switch and the other switches are single switches. 

When using this command:

`check_nwc_health --hostname 192.168.123.45 --mode list-interfaces`

I get this output:
```
000001 Vlan1
000200 Vlan200
000400 Vlan400
005001 Port-channel1
005179 StackPort1
005180 StackSub-St1-1
005181 StackSub-St1-2
005182 StackPort2
005183 StackSub-St2-1
005184 StackSub-St2-2
010101 GigabitEthernet1/0/1
010102 GigabitEthernet1/0/2
010103 GigabitEthernet1/0/3
010104 GigabitEthernet1/0/4
010105 GigabitEthernet1/0/5
010106 GigabitEthernet1/0/6
010107 GigabitEthernet1/0/7
010108 GigabitEthernet1/0/8
010109 GigabitEthernet1/0/9
010110 GigabitEthernet1/0/10
010111 GigabitEthernet1/0/11
010112 GigabitEthernet1/0/12
010113 GigabitEthernet1/0/13
010114 GigabitEthernet1/0/14
010115 GigabitEthernet1/0/15
OK - have fun
```

But I know there should be more interfaces, the following snmpwalk gives me more interfaces:

`snmpwalk -v2c -c public 192.168.123.45 1.3.6.1.2.1.31.1.1.1.1`

```
IF-MIB::ifName.1 = STRING: Vl1
IF-MIB::ifName.200 = STRING: Vl200
IF-MIB::ifName.400 = STRING: Vl400
IF-MIB::ifName.5001 = STRING: Po1
IF-MIB::ifName.5179 = STRING: StackPort1
IF-MIB::ifName.5180 = STRING: StackSub-St1-1
IF-MIB::ifName.5181 = STRING: StackSub-St1-2
IF-MIB::ifName.5182 = STRING: StackPort2
IF-MIB::ifName.5183 = STRING: StackSub-St2-1
IF-MIB::ifName.5184 = STRING: StackSub-St2-2
IF-MIB::ifName.10101 = STRING: Gi1/0/1
IF-MIB::ifName.10102 = STRING: Gi1/0/2
IF-MIB::ifName.10103 = STRING: Gi1/0/3
IF-MIB::ifName.10104 = STRING: Gi1/0/4
IF-MIB::ifName.10105 = STRING: Gi1/0/5
IF-MIB::ifName.10106 = STRING: Gi1/0/6
IF-MIB::ifName.10107 = STRING: Gi1/0/7
IF-MIB::ifName.10108 = STRING: Gi1/0/8
IF-MIB::ifName.10109 = STRING: Gi1/0/9
IF-MIB::ifName.10110 = STRING: Gi1/0/10
IF-MIB::ifName.10111 = STRING: Gi1/0/11
IF-MIB::ifName.10112 = STRING: Gi1/0/12
IF-MIB::ifName.10113 = STRING: Gi1/0/13
IF-MIB::ifName.10114 = STRING: Gi1/0/14
IF-MIB::ifName.10115 = STRING: Gi1/0/15
IF-MIB::ifName.10116 = STRING: Gi1/0/16
IF-MIB::ifName.10117 = STRING: Gi1/0/17
IF-MIB::ifName.10118 = STRING: Gi1/0/18
IF-MIB::ifName.10119 = STRING: Gi1/0/19
IF-MIB::ifName.10120 = STRING: Gi1/0/20
IF-MIB::ifName.10121 = STRING: Gi1/0/21
IF-MIB::ifName.10122 = STRING: Gi1/0/22
IF-MIB::ifName.10123 = STRING: Gi1/0/23
IF-MIB::ifName.10124 = STRING: Gi1/0/24
IF-MIB::ifName.10125 = STRING: Gi1/0/25
IF-MIB::ifName.10126 = STRING: Gi1/0/26
IF-MIB::ifName.10127 = STRING: Gi1/0/27
IF-MIB::ifName.10128 = STRING: Gi1/0/28
IF-MIB::ifName.10601 = STRING: Gi2/0/1
IF-MIB::ifName.10602 = STRING: Gi2/0/2
IF-MIB::ifName.10603 = STRING: Gi2/0/3
IF-MIB::ifName.10604 = STRING: Gi2/0/4
IF-MIB::ifName.10605 = STRING: Gi2/0/5
IF-MIB::ifName.10606 = STRING: Gi2/0/6
IF-MIB::ifName.10607 = STRING: Gi2/0/7
IF-MIB::ifName.10608 = STRING: Gi2/0/8
IF-MIB::ifName.10609 = STRING: Gi2/0/9
IF-MIB::ifName.10610 = STRING: Gi2/0/10
IF-MIB::ifName.10611 = STRING: Gi2/0/11
IF-MIB::ifName.10612 = STRING: Gi2/0/12
IF-MIB::ifName.10613 = STRING: Gi2/0/13
IF-MIB::ifName.10614 = STRING: Gi2/0/14
IF-MIB::ifName.10615 = STRING: Gi2/0/15
IF-MIB::ifName.10616 = STRING: Gi2/0/16
IF-MIB::ifName.10617 = STRING: Gi2/0/17
IF-MIB::ifName.10618 = STRING: Gi2/0/18
IF-MIB::ifName.10619 = STRING: Gi2/0/19
IF-MIB::ifName.10620 = STRING: Gi2/0/20
IF-MIB::ifName.10621 = STRING: Gi2/0/21
IF-MIB::ifName.10622 = STRING: Gi2/0/22
IF-MIB::ifName.10623 = STRING: Gi2/0/23
IF-MIB::ifName.10624 = STRING: Gi2/0/24
IF-MIB::ifName.10625 = STRING: Gi2/0/25
IF-MIB::ifName.10626 = STRING: Gi2/0/26
IF-MIB::ifName.10627 = STRING: Gi2/0/27
IF-MIB::ifName.10628 = STRING: Gi2/0/28
IF-MIB::ifName.14001 = STRING: Nu0
IF-MIB::ifName.14002 = STRING: Fa0
```

When using the ultra-verbose mode of check_nwc_health with this command:

`./check_nwc_health --hostname 192.168.123.45 --mode list-interfaces -vvvvvvvvvvv`

The output is very long, I pasted it here: http://pastebin.com/CxdqFZUQ

I don't know much about the internals of check_nwc_health but the lines 55 to 69 seem to be interesting.

**Comment by lausser** [comment]
Hi,

what about snmpwalk.... 1.3.6.1.2.1.2.2.1.2?

Do you see them all?



Gerhard



Von: Finn Christiansen [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. März 2015 15:17
An: lausser/check_nwc_health
Betreff: [check_nwc_health] Interfaces missing when querying Cisco Catalyst 
2960 switches (#34)



I am using check_nwc_health (currently version 3.4.3) and there seems to be 
a interface-related problem. When querying Cisco switches for 
interface-related data (tested with modes interface-usage, interface-status, 
list-interfaces, list-interfaces-detail) not all interfaces are shown.

I have seen this issue on different switches, e.g. C2960S and C2960X. One 
switch is a stacked switch and the other switches are single switches.

When using this command:

check_nwc_health --hostname 192.168.123.45 --mode list-interfaces

I get this output:

000001 Vlan1
000200 Vlan200
000400 Vlan400
005001 Port-channel1
005179 StackPort1
005180 StackSub-St1-1
005181 StackSub-St1-2
005182 StackPort2
005183 StackSub-St2-1
005184 StackSub-St2-2
010101 GigabitEthernet1/0/1
010102 GigabitEthernet1/0/2
010103 GigabitEthernet1/0/3
010104 GigabitEthernet1/0/4
010105 GigabitEthernet1/0/5
010106 GigabitEthernet1/0/6
010107 GigabitEthernet1/0/7
010108 GigabitEthernet1/0/8
010109 GigabitEthernet1/0/9
010110 GigabitEthernet1/0/10
010111 GigabitEthernet1/0/11
010112 GigabitEthernet1/0/12
010113 GigabitEthernet1/0/13
010114 GigabitEthernet1/0/14
010115 GigabitEthernet1/0/15
OK - have fun

But I know there should be more interfaces, the following snmpwalk gives me 
more interfaces:

snmpwalk -v2c -c public 192.168.123.45 1.3.6.1.2.1.31.1.1.1.1

IF-MIB::ifName.1 = STRING: Vl1
IF-MIB::ifName.200 = STRING: Vl200
IF-MIB::ifName.400 = STRING: Vl400
IF-MIB::ifName.5001 = STRING: Po1
IF-MIB::ifName.5179 = STRING: StackPort1
IF-MIB::ifName.5180 = STRING: StackSub-St1-1
IF-MIB::ifName.5181 = STRING: StackSub-St1-2
IF-MIB::ifName.5182 = STRING: StackPort2
IF-MIB::ifName.5183 = STRING: StackSub-St2-1
IF-MIB::ifName.5184 = STRING: StackSub-St2-2
IF-MIB::ifName.10101 = STRING: Gi1/0/1
IF-MIB::ifName.10102 = STRING: Gi1/0/2
IF-MIB::ifName.10103 = STRING: Gi1/0/3
IF-MIB::ifName.10104 = STRING: Gi1/0/4
IF-MIB::ifName.10105 = STRING: Gi1/0/5
IF-MIB::ifName.10106 = STRING: Gi1/0/6
IF-MIB::ifName.10107 = STRING: Gi1/0/7
IF-MIB::ifName.10108 = STRING: Gi1/0/8
IF-MIB::ifName.10109 = STRING: Gi1/0/9
IF-MIB::ifName.10110 = STRING: Gi1/0/10
IF-MIB::ifName.10111 = STRING: Gi1/0/11
IF-MIB::ifName.10112 = STRING: Gi1/0/12
IF-MIB::ifName.10113 = STRING: Gi1/0/13
IF-MIB::ifName.10114 = STRING: Gi1/0/14
IF-MIB::ifName.10115 = STRING: Gi1/0/15
IF-MIB::ifName.10116 = STRING: Gi1/0/16
IF-MIB::ifName.10117 = STRING: Gi1/0/17
IF-MIB::ifName.10118 = STRING: Gi1/0/18
IF-MIB::ifName.10119 = STRING: Gi1/0/19
IF-MIB::ifName.10120 = STRING: Gi1/0/20
IF-MIB::ifName.10121 = STRING: Gi1/0/21
IF-MIB::ifName.10122 = STRING: Gi1/0/22
IF-MIB::ifName.10123 = STRING: Gi1/0/23
IF-MIB::ifName.10124 = STRING: Gi1/0/24
IF-MIB::ifName.10125 = STRING: Gi1/0/25
IF-MIB::ifName.10126 = STRING: Gi1/0/26
IF-MIB::ifName.10127 = STRING: Gi1/0/27
IF-MIB::ifName.10128 = STRING: Gi1/0/28
IF-MIB::ifName.10601 = STRING: Gi2/0/1
IF-MIB::ifName.10602 = STRING: Gi2/0/2
IF-MIB::ifName.10603 = STRING: Gi2/0/3
IF-MIB::ifName.10604 = STRING: Gi2/0/4
IF-MIB::ifName.10605 = STRING: Gi2/0/5
IF-MIB::ifName.10606 = STRING: Gi2/0/6
IF-MIB::ifName.10607 = STRING: Gi2/0/7
IF-MIB::ifName.10608 = STRING: Gi2/0/8
IF-MIB::ifName.10609 = STRING: Gi2/0/9
IF-MIB::ifName.10610 = STRING: Gi2/0/10
IF-MIB::ifName.10611 = STRING: Gi2/0/11
IF-MIB::ifName.10612 = STRING: Gi2/0/12
IF-MIB::ifName.10613 = STRING: Gi2/0/13
IF-MIB::ifName.10614 = STRING: Gi2/0/14
IF-MIB::ifName.10615 = STRING: Gi2/0/15
IF-MIB::ifName.10616 = STRING: Gi2/0/16
IF-MIB::ifName.10617 = STRING: Gi2/0/17
IF-MIB::ifName.10618 = STRING: Gi2/0/18
IF-MIB::ifName.10619 = STRING: Gi2/0/19
IF-MIB::ifName.10620 = STRING: Gi2/0/20
IF-MIB::ifName.10621 = STRING: Gi2/0/21
IF-MIB::ifName.10622 = STRING: Gi2/0/22
IF-MIB::ifName.10623 = STRING: Gi2/0/23
IF-MIB::ifName.10624 = STRING: Gi2/0/24
IF-MIB::ifName.10625 = STRING: Gi2/0/25
IF-MIB::ifName.10626 = STRING: Gi2/0/26
IF-MIB::ifName.10627 = STRING: Gi2/0/27
IF-MIB::ifName.10628 = STRING: Gi2/0/28
IF-MIB::ifName.14001 = STRING: Nu0
IF-MIB::ifName.14002 = STRING: Fa0

When using the ultra-verbose mode of check_nwc_health with this command:

./check_nwc_health --hostname 192.168.123.45 --mode 
list-interfaces -vvvvvvvvvvv

The output is very long, I pasted it here: http://pastebin.com/CxdqFZUQ

I don't know much about the internals of check_nwc_health but the lines 55 
to 69 seem to be interesting.

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/34> . 
<https://github.com/notifications/beacon/AAMJOLUshUQWFgxHETUkeP0UoYZ1NLoeks5n4rr0gaJpZM4D0iLw.gif>

**Comment by Finn10111** [comment]
Hi,

> what about snmpwalk.... 1.3.6.1.2.1.2.2.1.2?

> Do you see them all?

Yes, I can see them all (68 interfaces)

**Comment by lausser** [comment]
Please search for " # get mini-version of a table" in the plugin. A few 
lines below there is

      my $ifresult = $self->get_entries(

          -columns => \@columns,

      );

After this, please insert:



printf "get_entries returned %d oids\n", scalar(keys %{$ifresult});



Then, ~15 lines below, there is another my $ifresult = $self->get_entries...

Here also, add the same printf-line after it.



Run --mode list-interfaces again. What's the number in ""get_entries 
returned ... oids"?



Gerhard



Von: Finn Christiansen [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. März 2015 16:23
An: lausser/check_nwc_health
Cc: Gerhard Lausser
Betreff: Re: [check_nwc_health] Interfaces missing when querying Cisco 
Catalyst 2960 switches (#34)



Hi,

what about snmpwalk.... 1.3.6.1.2.1.2.2.1.2?

Do you see them all?

Yes, I can see them all (68 interfaces)

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/34#issuecomment-86080731> 
. 
<https://github.com/notifications/beacon/AAMJOOxt1EmrtpOOllloNJRSk2KK2SB4ks5n4spQgaJpZM4D0iLw.gif>

**Comment by Finn10111** [comment]
I added these two lines and get this:

```
get_entries returned 50 oids
get_entries returned 136 oids
```

**Comment by lausser** [comment]
not good. fetching ifTable returns only 25 interfaces. maybe a buffer thing.

Again, find the line with "# get mini-version of a table

After it, insert:

$self->mult_snmp_max_msg_size()

and run again. Still 50/136 oids?



Von: Finn Christiansen [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. März 2015 16:44
An: lausser/check_nwc_health
Cc: Gerhard Lausser
Betreff: Re: [check_nwc_health] Interfaces missing when querying Cisco 
Catalyst 2960 switches (#34)



I added these two lines and get this:

get_entries returned 50 oids
get_entries returned 136 oids

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/34#issuecomment-86088215> 
. 
<https://github.com/notifications/beacon/AAMJOH7Tyf4l8v4xepl2vtioZJzs0odFks5n4s8ygaJpZM4D0iLw.gif>

**Comment by Finn10111** [comment]
Yes, still the same. I also deleted the interface_cache file in the temporary directory after adding the mult_snmp_max_msg_size() function but it's still the same.

**Comment by lausser** [comment]
After the "# get mini-version of a table"-line, add

$GLPlugin::SNMP::session->debug(0xff);



this generates a large amount of output. Better redirect it to a file (.... 
 > list-interfaces.txt 2>&1) including stderr.



Von: Finn Christiansen [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. März 2015 16:52
An: lausser/check_nwc_health
Cc: Gerhard Lausser
Betreff: Re: [check_nwc_health] Interfaces missing when querying Cisco 
Catalyst 2960 switches (#34)



Yes, still the same. I also deleted the interface_cache file in the 
temporary directory after adding the mult_snmp_max_msg_size() function but 
it's still the same.

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/34#issuecomment-86092499> 
. 
<https://github.com/notifications/beacon/AAMJOGVjFsMYzTwUDRc92Pnf7-ai4iwYks5n4tEQgaJpZM4D0iLw.gif>

**Comment by Finn10111** [comment]
Done: http://paste.finnchristiansen.de/plpgogsc2

**Comment by lausser** [comment]
Hi,
checkout the last changes from git and try again. Now it should work.
Gerhard

**Comment by Finn10111** [comment]
Now it works and I can see all interfaces including its perfdata. Thanks!
