### ISSUE TITLE
ME-3600 reports warning with temperature sensors which are not active

### ISSUE THREAD

**Issue by snoep** [lausser/check_nwc_health#35]
Hi,

I use the check_nwc plugin heavily - it makes life so much easier. However, I encounter a problem:

Running 3.4.2 with hardware-health on a Cisco ME-3600x reports:
WARNING - temperature 1 SW#1, Sensor#3, YELLOW is warning, temperature 2 SW#1, Sensor#5, YELLOW is warning 

While the sh env all reports
FAN in PS-1 is OK
FAN in PS-2 is OK
SYSTEM TEMPERATURE is GREEN
SYSTEM Temperature Value: 40.0 Degree Celsius
SYSTEM Temperature State: GREEN
SYSTEM Low Temperature Alert Threshold: 0.0 Degree Celsius
SYSTEM Low Temperature Shutdown Threshold: -20.0 Degree Celsius
SYSTEM High Temperature Alert Threshold: 58.0 Degree Celsius
SYSTEM High Temperature Shutdown Threshold: 80.0 Degree Celsius
POWER SUPPLY 1 Temperature Value: 41.7500 Degree Celsius
POWER SUPPLY 1 Temperature Alert Threshold: 85.0000 Degree Celsius
POWER SUPPLY 1 Temperature Shutdown Threshold: 110.0000 Degree Celsius
POWER SUPPLY 2 Temperature Value: 43.7500 Degree Celsius
POWER SUPPLY 2 Temperature Alert Threshold: 85.0000 Degree Celsius
POWER SUPPLY 2 Temperature Shutdown Threshold: 110.0000 Degree Celsius
POWER SUPPLY 1 is AC OK
POWER SUPPLY 2 is AC OK

ALARM CONTACT 1 is not asserted
ALARM CONTACT 2 is not asserted
ALARM CONTACT 3 is not asserted
ALARM CONTACT 4 is not asserted

The check command with -v shows
I am a Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.4(3)S2, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Wed 28-Jan-15 16:04 by prod_rel_team
WARNING - temperature 1 SW#1, Sensor#3, YELLOW  is warning, temperature 2 SW#1, Sensor#5, YELLOW  is warning
checking fans
fan 0 (Switch#1, Fan#1) is normal
fan 0 (Switch#1, Fan#2) is normal
checking temperatures
temperature 0 SW#1, Sensor#1, GREEN  is 40 (of 80 max = normal)
temperature 1 SW#1, Sensor#3, YELLOW  is warning
temperature 2 SW#1, Sensor#5, YELLOW  is warning
temperature 3 SW#1, PowerSupply#1, GREEN  is 41 (of 80 max = normal)
temperature 4 SW#1, PowerSupply#2, GREEN  is 43 (of 80 max = normal)
checking voltages
checking supplies
powersupply 0 (Switch#1, PowerSupply 1) is normal
powersupply 0 (Switch#1, PowerSupply 2) is normal | 'temp_0'=40;80 'temp_3'=41;80 'temp_4'=43;80

I have tried to blacklist these, however to no avail.

Any suggestions ?

Many thanks
Paul

**Comment by lausser** [comment]
Hi,



you can run "check_nwc_health .... -vv", then you get a detailed list of the 
monitored items, something like

[TEMPERATURE_1]

tempIndex = 1

tempValue = 40

....

[TEMPERATURE_2]

....



The section headers can be used as arguments for the blacklisting, 
like --blacklist TEMPERATURE_1,TEMPERATURE_2



You could also run "check_nwc_health .... --mode walk", which gives you two 
snmpwalk commands. Execute these commands and mail the resulting file to me, 
please.



Gerhard





Von: snoep [mailto:notifications@github.com]
Gesendet: Mittwoch, 8. April 2015 12:31
An: lausser/check_nwc_health
Betreff: [check_nwc_health] ME-3600 reports warning with temperature sensors 
which are not active (#35)



Hi,

I use the check_nwc plugin heavily - it makes life so much easier. However, 
I encounter a problem:

Running 3.4.2 with hardware-health on a Cisco ME-3600x reports:
WARNING - temperature 1 SW#1, Sensor#3, YELLOW is warning, temperature 2 
SW#1, Sensor#5, YELLOW is warning

While the sh env all reports
FAN in PS-1 is OK
FAN in PS-2 is OK
SYSTEM TEMPERATURE is GREEN
SYSTEM Temperature Value: 40.0 Degree Celsius
SYSTEM Temperature State: GREEN
SYSTEM Low Temperature Alert Threshold: 0.0 Degree Celsius
SYSTEM Low Temperature Shutdown Threshold: -20.0 Degree Celsius
SYSTEM High Temperature Alert Threshold: 58.0 Degree Celsius
SYSTEM High Temperature Shutdown Threshold: 80.0 Degree Celsius
POWER SUPPLY 1 Temperature Value: 41.7500 Degree Celsius
POWER SUPPLY 1 Temperature Alert Threshold: 85.0000 Degree Celsius
POWER SUPPLY 1 Temperature Shutdown Threshold: 110.0000 Degree Celsius
POWER SUPPLY 2 Temperature Value: 43.7500 Degree Celsius
POWER SUPPLY 2 Temperature Alert Threshold: 85.0000 Degree Celsius
POWER SUPPLY 2 Temperature Shutdown Threshold: 110.0000 Degree Celsius
POWER SUPPLY 1 is AC OK
POWER SUPPLY 2 is AC OK

ALARM CONTACT 1 is not asserted
ALARM CONTACT 2 is not asserted
ALARM CONTACT 3 is not asserted
ALARM CONTACT 4 is not asserted

The check command with -v shows
I am a Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 
15.4(3)S2, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Wed 28-Jan-15 16:04 by prod_rel_team
WARNING - temperature 1 SW#1, Sensor#3, YELLOW is warning, temperature 2 
SW#1, Sensor#5, YELLOW is warning
checking fans
fan 0 (Switch#1, Fan#1) is normal
fan 0 (Switch#1, Fan#2) is normal
checking temperatures
temperature 0 SW#1, Sensor#1, GREEN is 40 (of 80 max = normal)
temperature 1 SW#1, Sensor#3, YELLOW is warning
temperature 2 SW#1, Sensor#5, YELLOW is warning
temperature 3 SW#1, PowerSupply#1, GREEN is 41 (of 80 max = normal)
temperature 4 SW#1, PowerSupply#2, GREEN is 43 (of 80 max = normal)
checking voltages
checking supplies
powersupply 0 (Switch#1, PowerSupply 1) is normal
powersupply 0 (Switch#1, PowerSupply 2) is normal | 'temp_0'=40;80 
'temp_3'=41;80 'temp_4'=43;80

I have tried to blacklist these, however to no avail.

Any suggestions ?

Many thanks
Paul

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/35> . 
<https://github.com/notifications/beacon/AAMJOJMGDt0WCz4IsPltoZG0bDZYMj10ks5n9PrjgaJpZM4D8U06.gif>

**Comment by snoep** [comment]
:) Great stuff. SIMPLE_1007 and SIMPLE_1009 were the results - blacklisted. Script output now ok.

Many thanks!

**Comment by snoep** [comment]
Hi,
snmpwalk as requested is available at http://topmaf.org/files/data.tgz

Please indicate when file is downloaded, so I can remove it from the site.

Cheers
Paul

**Comment by lausser** [comment]
Hi,

i got it, you can delete the file.



Gerhard



Von: snoep [mailto:notifications@github.com]
Gesendet: Donnerstag, 9. April 2015 21:24
An: lausser/check_nwc_health
Cc: Gerhard Lausser
Betreff: Re: [check_nwc_health] ME-3600 reports warning with temperature 
sensors which are not active (#35)



Hi,
snmpwalk as requested is available at http://topmaf.org/files/data.tgz

Please indicate when file is downloaded, so I can remove it from the site.

Cheers
Paul

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/35#issuecomment-91333411> 
. 
<https://github.com/notifications/beacon/AAMJONuTM8APTOUbHP15aaaqj2VhLiDzks5n9slKgaJpZM4D8U06.gif>

**Comment by snoep** [comment]
Done - thanks for the help.
