### ISSUE TITLE
Error of initialized value  

### ISSUE THREAD

**Issue by hogsim** [lausser/check_nwc_health#37]
Hello, 
I got a problem with the plugins , i compiled the last version ( 4.1) When i run the command:

./check_nwc_health --hostname cn2 --timeout 10 --community public  --mode interface-usage --name TenGigabitEthernet1/5/3

here is the results: 

Use of uninitialized value in sprintf at ./check_nwc_health line 1026.
Use of uninitialized value in division (/) at ./check_nwc_health line 1027.
Use of uninitialized value in sprintf at ./check_nwc_health line 1026.
Use of uninitialized value in division (/) at ./check_nwc_health line 1027.
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 9798.
Use of uninitialized value in multiplication (*) at ./check_nwc_health line 9800.
Use of uninitialized value in division (/) at ./check_nwc_health line 9823.
Use of uninitialized value in division (/) at ./check_nwc_health line 9824.
OK - interface TenGigabitEthernet1/5/3 usage is in:0.00% (0.00Bits/s) out:0.00% (0.00Bits/s) | 'TenGigabitEthernet1/5/3_usage_in'=0%;80;90;0;100 'TenGigabitEthernet1/5/3_usage_out'=0%;80;90;0;100 'TenGigabitEthernet1/5/3_traffic_in'=0;800000000;900000000;0;1000000000 'TenGigabitEthernet1/5/3_traffic_out'=0;800000000;900000000;0;1000000000

And the usage is shown as 0,00% but I know that there is trafic. 

Is there a way to fix that? 
Thanks

**Comment by socrates324** [comment]
Hi,
had the exact same proble, mit it seems to be rectified in the latest version 4.2

cheers
socrates324

**Comment by unbreakabl3** [comment]
Do you have any idea, when the 4.2 will be released?

**Comment by hogsim** [comment]
Hey, 
yeah seems corrected. No problems anymore. 
It's already released. 
In the download section: https://labs.consol.de/nagios/check_nwc_health/

**Comment by unbreakabl3** [comment]
Thank you!!!!
