### ISSUE TITLE
Detect failed power supply in Checkpoint

### ISSUE THREAD

**Issue by Napsty** [lausser/check_nwc_health#46]
Currently check_nwc_health does not detect when a power supply is down in Checkpoint running on Nokia harddware.

	# ./check_nwc_health --hostname 1.2.3.4 --community public --mode hardware-health  -v -v
	I am a Linux checkpoint1 2.6.18-92cp #1 SMP Wed Apr 8 15:46:38 IDT 2015 i686
	[DISKSUBSYSTEM]
	diskPercent: 86
	info: checking disks

	[STORAGE_31]
	hrStorageAllocationUnits: 4096
	hrStorageDescr: /
	hrStorageIndex: 31
	hrStorageSize: 8125916
	hrStorageType: hrStorageFixedDisk
	hrStorageUsed: 1093091
	info: storage 31 (/) has 86.55% free space left

	[STORAGE_32]
	hrStorageAllocationUnits: 1024
	hrStorageDescr: /boot
	hrStorageIndex: 32
	hrStorageSize: 147692
	hrStorageType: hrStorageFixedDisk
	hrStorageUsed: 87030
	info: storage 32 (/boot) has 41.07% free space left

	[STORAGE_33]
	hrStorageAllocationUnits: 4096
	hrStorageDescr: /var/log
	hrStorageIndex: 33
	hrStorageSize: 38090235
	hrStorageType: hrStorageFixedDisk
	hrStorageUsed: 5424730
	info: storage 33 (/var/log) has 85.76% free space left

	[TEMPERATURESUBSYSTEM]

	[TEMPERATURE_1.0]
	sensorsTemperatureIndex: 1
	sensorsTemperatureName: CPU Temp
	sensorsTemperatureStatus: normal
	sensorsTemperatureType: Temperature
	sensorsTemperatureUOM: degrees C
	sensorsTemperatureValue: 43
	info: temperature CPU Temp is normal (43 degrees C)

	[TEMPERATURE_2.0]
	sensorsTemperatureIndex: 2
	sensorsTemperatureName: System Temp
	sensorsTemperatureStatus: normal
	sensorsTemperatureType: Temperature
	sensorsTemperatureUOM: degrees C
	sensorsTemperatureValue: 34
	info: temperature System Temp is normal (34 degrees C)

	[FANSUBSYSTEM]

	[FAN_1.0]
	sensorsFanIndex: 1
	sensorsFanName: Case Fan 1
	sensorsFanStatus: normal
	sensorsFanType: Fan
	sensorsFanUOM: RPM
	sensorsFanValue: 5273
	info: fan Case Fan 1 is normal (5273 RPM)

	[FAN_2.0]
	sensorsFanIndex: 2
	sensorsFanName: Case Fan 2
	sensorsFanStatus: normal
	sensorsFanType: Fan
	sensorsFanUOM: RPM
	sensorsFanValue: 5625
	info: fan Case Fan 2 is normal (5625 RPM)

	[FAN_3.0]
	sensorsFanIndex: 3
	sensorsFanName: Case Fan 3
	sensorsFanStatus: normal
	sensorsFanType: Fan
	sensorsFanUOM: RPM
	sensorsFanValue: 5443
	info: fan Case Fan 3 is normal (5443 RPM)

	[VOLTAGESUBSYSTEM]

	[VOLTAGE_1.0]
	sensorsVoltageIndex: 1
	sensorsVoltageName: 3Vbat
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 3.12
	info: voltage 3Vbat is normal (3.12 Volts)

	[VOLTAGE_2.0]
	sensorsVoltageIndex: 2
	sensorsVoltageName: 3VSB
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 3.36
	info: voltage 3VSB is normal (3.36 Volts)

	[VOLTAGE_3.0]
	sensorsVoltageIndex: 3
	sensorsVoltageName: Vtt
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 1.10
	info: voltage Vtt is normal (1.10 Volts)

	[VOLTAGE_4.0]
	sensorsVoltageIndex: 4
	sensorsVoltageName: 5V
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 5.20
	info: voltage 5V is normal (5.20 Volts)

	[VOLTAGE_5.0]
	sensorsVoltageIndex: 5
	sensorsVoltageName: 1.5V
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 1.52
	info: voltage 1.5V is normal (1.52 Volts)

	[VOLTAGE_6.0]
	sensorsVoltageIndex: 6
	sensorsVoltageName: 3.3V
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 3.39
	info: voltage 3.3V is normal (3.39 Volts)

	[VOLTAGE_7.0]
	sensorsVoltageIndex: 7
	sensorsVoltageName: +12V
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 12.20
	info: voltage +12V is normal (12.20 Volts)

	[VOLTAGE_8.0]
	sensorsVoltageIndex: 8
	sensorsVoltageName: Vcore
	sensorsVoltageStatus: normal
	sensorsVoltageType: Voltage
	sensorsVoltageUOM: Volts
	sensorsVoltageValue: 1.10
	info: voltage Vcore is normal (1.10 Volts)

	OK - environmental hardware working fine
	checking disks
	storage 31 (/) has 86.55% free space left
	storage 32 (/boot) has 41.07% free space left
	storage 33 (/var/log) has 85.76% free space left
	temperature CPU Temp is normal (43 degrees C)
	temperature System Temp is normal (34 degrees C)
	fan Case Fan 1 is normal (5273 RPM)
	fan Case Fan 2 is normal (5625 RPM)
	fan Case Fan 3 is normal (5443 RPM)
	voltage 3Vbat is normal (3.12 Volts)
	voltage 3VSB is normal (3.36 Volts)
	voltage Vtt is normal (1.10 Volts)
	voltage 5V is normal (5.20 Volts)
	voltage 1.5V is normal (1.52 Volts)
	voltage 3.3V is normal (3.39 Volts)
	voltage +12V is normal (12.20 Volts)
	voltage Vcore is normal (1.10 Volts) | '/_free_pct'=86.55%;10:;5:;0;100 '/boot_free_pct'=41.07%;10:;5:;0;100 '/var/log_free_pct'=85.76%;10:;5:;0;100 'temperature_CPU Temp'=43;60;70;; 'temperature_System Temp'=34;60;70;; 'fanCase Fan 1_rpm'=5273;60;70;; 'fanCase Fan 2_rpm'=5625;60;70;; 'fanCase Fan 3_rpm'=5443;60;70;; 'voltage3Vbat_rpm'=3.12;60;70;; 'voltage3VSB_rpm'=3.36;60;70;; 'voltageVtt_rpm'=1.10;60;70;; 'voltage5V_rpm'=5.20;60;70;; 'voltage1.5V_rpm'=1.52;60;70;; 'voltage3.3V_rpm'=3.39;60;70;; 'voltage+12V_rpm'=12.20;60;70;; 'voltageVcore_rpm'=1.10;60;70;;

The relevant information can be found in the powerSupplyTable (1.3.6.1.4.1.2620.1.6.7.9.1):

    # snmpwalk -v 2c -c public 1.2.3.4 1.3.6.1.4.1.2620.1.6.7.9.1
    iso.3.6.1.4.1.2620.1.6.7.9.1.1.1.1.0 = INTEGER: 1
    iso.3.6.1.4.1.2620.1.6.7.9.1.1.1.2.0 = INTEGER: 2
    iso.3.6.1.4.1.2620.1.6.7.9.1.1.2.1.0 = STRING: "Up"
    iso.3.6.1.4.1.2620.1.6.7.9.1.1.2.2.0 = STRING: "Down"

**Comment by Napsty** [comment]
Hi just created a pull request which adds the Power Supply check into the hardware-health check for Checkpoint devices. However I was not able to add the new package to the final plugin during compile. I got the following error:

    Can't locate object method "new" via package "Classes::CheckPoint::Firewall1::Component::PowersupplySubsystem" (perhaps you forgot to load "Classes::CheckPoint::Firewall1::Component::PowersupplySubsystem"?) at ./check_nwc_health_new line 12861.

Once I manually added the new PowersupplySubsystem into the final compiled plugin, it works:

    # ./check_nwc_health_new --hostname 1.2.3.4 --community public --mode hardware-health 
    CRITICAL - power supply 2 status is Down, storage 31 (/) has 86.55% free space left, storage 32 (/boot) has 41.07% free space left, storage 33 (/var/log) has 85.76% free space left, temperature CPU Temp is normal (40 degrees C), temperature System Temp is normal (34 degrees C), fan Case Fan 1 is normal (5443 RPM), fan Case Fan 2 is normal (5818 RPM), fan Case Fan 3 is normal (5273 RPM), voltage 3Vbat is normal (3.12 Volts), voltage 3VSB is normal (3.36 Volts), voltage Vtt is normal (1.10 Volts), voltage 5V is normal (5.20 Volts), voltage 1.5V is normal (1.52 Volts), voltage 3.3V is normal (3.39 Volts), voltage +12V is normal (12.20 Volts), voltage Vcore is normal (1.13 Volts), power supply 1 status is Up | '/_free_pct'=86.55%;10:;5:;0;100 '/boot_free_pct'=41.07%;10:;5:;0;100 '/var/log_free_pct'=85.76%;10:;5:;0;100 'temperature_CPU Temp'=40.50;60;70;; 'temperature_System Temp'=34;60;70;; 'fanCase Fan 1_rpm'=5443;60;70;; 'fanCase Fan 2_rpm'=5818;60;70;; 'fanCase Fan 3_rpm'=5273;60;70;; 'voltage3Vbat_rpm'=3.12;60;70;; 'voltage3VSB_rpm'=3.36;60;70;; 'voltageVtt_rpm'=1.10;60;70;; 'voltage5V_rpm'=5.20;60;70;; 'voltage1.5V_rpm'=1.52;60;70;; 'voltage3.3V_rpm'=3.39;60;70;; 'voltage+12V_rpm'=12.20;60;70;; 'voltageVcore_rpm'=1.13;60;70;;

There's probably some additional change required to include that file in the compile task but I cannot see where.

**Comment by Napsty** [comment]
Found it in Makefile.am ^_^v

**Comment by lausser** [comment]
pull request pulled
