### ISSUE TITLE
MIB Implementation check gives wrong result in simulation mode

### ISSUE THREAD

**Issue by dhoffend** [lausser/check_nwc_health#48]
Checking for a supported MIB gives wrong result when a similar MIB is available:

Example:

    $ ./check_nwc_health -vvv --snmpwalk simulation.txt --mode supportedmibs | grep 1.3.6.1.4.1.9.9.13
    implements CISCO-ENTITY-ALARM-MIB 1.3.6.1.4.1.9.9.138.1
    implements CISCO-ENVMON-MIB 1.3.6.1.4.1.9.9.13

Simulation Data:

    $ grep 1.3.6.1.4.1.9.9.13 PPD88138.snmpwalk.txt | cut -d. -f -11 | uniq -c
    761 .1.3.6.1.4.1.9.9.138.1

**Comment by lausser** [comment]
pulled
