### ISSUE TITLE
--warningx and --criticalx not working

### ISSUE THREAD

**Issue by milleroff** [lausser/check_nwc_health#50]
Hello.

I have a monitoring host running icinga2.
The service is defined with variables:

```
# icinga2 object list --type Service --name "if-5" | egrep "(check_command|nwc)"

* check_command = "nwc_health"
    * nwc_health_community = "xxxxxxxx"
    * nwc_health_criticalx = "GigaEthernet0/5_discards_in=100"
    * nwc_health_mode = "interface-health"
    * nwc_health_name = "GigaEthernet0/5"
    * nwc_health_regexp = false
    * nwc_health_units = "MBi"
    * nwc_health_warningx = "GigaEthernet0/5_discards_in=50"
```

In the Icinga2 web interface i see the critical and warning value set correctly:

![github](https://cloud.githubusercontent.com/assets/1090680/11935443/8501d82e-a810-11e5-84cf-eca7fd0b9d6c.png)

The problem is i still receive Warning Notifications:

![telegram](https://cloud.githubusercontent.com/assets/1090680/11935725/15ce1736-a812-11e5-8ca8-d8aac5d892ee.png)

**Comment by lausser** [comment]
I tried to reproduce it. Here it works as intended. Did you update to a recent version? 5.3.2?
