### ISSUE TITLE
SNMP results with Hex-STRING data is processed wrongly

### ISSUE THREAD

**Issue by dhoffend** [lausser/check_nwc_health#51]
This is a problem when you try to compare Live SNMP requests with the result of a snmpwalk simulation file.

Net-SNMP returns the Hex-STRING data as "packed" binary stream while the snmpwalk simulation function reads the data as "0x01 00 00 00 00 ...".

Right now I don't know which functions of check_nwc_health are based on hex-data so I don't know which parts are afffected.

**Comment by lausser** [comment]
pullrequest
