### ISSUE TITLE
CISCO-ENTITY-ALARM-MIB doesn't work with live data

### ISSUE THREAD

**Issue by dhoffend** [lausser/check_nwc_health#52]
The snmp attribute cefcAlarmList contains a Hex-String "SYNTAX OCTET STRING (SIZE (0..32))". When using the live data, snmpwalk is actually returning the result as packed data while the simulation returns some hex data as string. (This is linked to issue #51)

The result: The AlarmSubSystem is correctly working and announcing failed entities while the run using live data is ending withing problems parsing and processing the hex data.

**Comment by dhoffend** [comment]
https://github.com/lausser/check_nwc_health/blob/master/plugins-scripts/Classes/Cisco/CISCOENTITYALARMMIB/Component/AlarmSubsystem.pm#L67

This foreach line will never work when using live-data.

**Comment by lausser** [comment]
pulled
