### ISSUE TITLE
Cisco / wrong messages with powersupply Faulty

### ISSUE THREAD

**Issue by ClemensBW** [lausser/check_nwc_health#56]
Hello,

i get a wrong status for some cisco devices with the "PS1 Faulty", nwc say that is critical, but at the IOS cli all locks fine.

[x]# ./check_nwc_health --mode hardware-health --hostname  10.x.8   --community XX
CRITICAL - powersupply 4034 (Sw4, PS1 Faulty, RPS NotExist) is notFunctioning | 'temp_1006'=24;60;;; 'temp_2006'=25;60;;; 'temp_3006'=24;60;;; 'temp_4006'=22;60;;;

debug check_nwc_health:
[x]# ./check_nwc_health -vvv --mode hardware-health --hostname  10.XXX.8 --community XXX
I am a Cisco IOS Software, C3750E Software (C3750E-IPBASEK9-M), Version 12.2(55)SE7, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Mon 28-Jan-13 09:55 by prod_rel_team
[FANSUBSYSTEM]
info: checking fans

[FAN_1035]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#1, Fan#1
ciscoEnvMonFanStatusIndex: 1035
info: fan 1035 (Switch#1, Fan#1) is normal

[FAN_1036]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#1, Fan#2
ciscoEnvMonFanStatusIndex: 1036
info: fan 1036 (Switch#1, Fan#2) is normal

[FAN_2035]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#2, Fan#1
ciscoEnvMonFanStatusIndex: 2035
info: fan 2035 (Switch#2, Fan#1) is normal

[FAN_3035]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#3, Fan#1
ciscoEnvMonFanStatusIndex: 3035
info: fan 3035 (Switch#3, Fan#1) is normal

[FAN_4035]
ciscoEnvMonFanState: normal
ciscoEnvMonFanStatusDescr: Switch#4, Fan#1
ciscoEnvMonFanStatusIndex: 4035
info: fan 4035 (Switch#4, Fan#1) is normal

[TEMPERATURESUBSYSTEM]
info: checking temperatures

[TEMPERATURE_1006]
ciscoEnvMonTemperatureLastShutdown: 0
ciscoEnvMonTemperatureState: normal
ciscoEnvMonTemperatureStatusDescr: SW#1, Sensor#1, GREEN 
ciscoEnvMonTemperatureStatusIndex: 1006
ciscoEnvMonTemperatureStatusValue: 24
ciscoEnvMonTemperatureThreshold: 60
info: temperature 1006 SW#1, Sensor#1, GREEN  is 24 (of 60 max = normal)

[TEMPERATURE_2006]
ciscoEnvMonTemperatureLastShutdown: 0
ciscoEnvMonTemperatureState: normal
ciscoEnvMonTemperatureStatusDescr: SW#2, Sensor#1, GREEN 
ciscoEnvMonTemperatureStatusIndex: 2006
ciscoEnvMonTemperatureStatusValue: 25
ciscoEnvMonTemperatureThreshold: 60
info: temperature 2006 SW#2, Sensor#1, GREEN  is 25 (of 60 max = normal)

[TEMPERATURE_3006]
ciscoEnvMonTemperatureLastShutdown: 0
ciscoEnvMonTemperatureState: normal
ciscoEnvMonTemperatureStatusDescr: SW#3, Sensor#1, GREEN 
ciscoEnvMonTemperatureStatusIndex: 3006
ciscoEnvMonTemperatureStatusValue: 24
ciscoEnvMonTemperatureThreshold: 60
info: temperature 3006 SW#3, Sensor#1, GREEN  is 24 (of 60 max = normal)

[TEMPERATURE_4006]
ciscoEnvMonTemperatureLastShutdown: 0
ciscoEnvMonTemperatureState: normal
ciscoEnvMonTemperatureStatusDescr: SW#4, Sensor#1, GREEN 
ciscoEnvMonTemperatureStatusIndex: 4006
ciscoEnvMonTemperatureStatusValue: 22
ciscoEnvMonTemperatureThreshold: 60
info: temperature 4006 SW#4, Sensor#1, GREEN  is 22 (of 60 max = normal)

[VOLTAGESUBSYSTEM]
info: checking voltages

[POWERSUPPLYSUBSYSTEM]
info: checking supplies

[POWERSUPPLY_1034]
ciscoEnvMonSupplySource: 2
ciscoEnvMonSupplyState: normal
ciscoEnvMonSupplyStatusDescr: Sw1, PS1 Normal, RPS NotExist
ciscoEnvMonSupplyStatusIndex: 1034
info: powersupply 1034 (Sw1, PS1 Normal, RPS NotExist) is normal

[POWERSUPPLY_2034]
ciscoEnvMonSupplySource: 2
ciscoEnvMonSupplyState: normal
ciscoEnvMonSupplyStatusDescr: Sw2, PS1 Normal, RPS NotExist
ciscoEnvMonSupplyStatusIndex: 2034
info: powersupply 2034 (Sw2, PS1 Normal, RPS NotExist) is normal

[POWERSUPPLY_3034]
ciscoEnvMonSupplySource: 2
ciscoEnvMonSupplyState: normal
ciscoEnvMonSupplyStatusDescr: Sw3, PS1 Normal, RPS NotExist
ciscoEnvMonSupplyStatusIndex: 3034
info: powersupply 3034 (Sw3, PS1 Normal, RPS NotExist) is normal

[POWERSUPPLY_4034]
ciscoEnvMonSupplySource: 2
ciscoEnvMonSupplyState: notFunctioning
ciscoEnvMonSupplyStatusDescr: Sw4, PS1 Faulty, RPS NotExist
ciscoEnvMonSupplyStatusIndex: 4034
info: powersupply 4034 (Sw4, PS1 Faulty, RPS NotExist) is notFunctioning

CRITICAL - powersupply 4034 (Sw4, PS1 Faulty, RPS NotExist) is notFunctioning
checking fans
fan 1035 (Switch#1, Fan#1) is normal
fan 1036 (Switch#1, Fan#2) is normal
fan 2035 (Switch#2, Fan#1) is normal
fan 3035 (Switch#3, Fan#1) is normal
fan 4035 (Switch#4, Fan#1) is normal
checking temperatures
temperature 1006 SW#1, Sensor#1, GREEN  is 24 (of 60 max = normal)
temperature 2006 SW#2, Sensor#1, GREEN  is 25 (of 60 max = normal)
temperature 3006 SW#3, Sensor#1, GREEN  is 24 (of 60 max = normal)
temperature 4006 SW#4, Sensor#1, GREEN  is 22 (of 60 max = normal)
checking voltages
checking supplies
powersupply 1034 (Sw1, PS1 Normal, RPS NotExist) is normal
powersupply 2034 (Sw2, PS1 Normal, RPS NotExist) is normal
powersupply 3034 (Sw3, PS1 Normal, RPS NotExist) is normal
powersupply 4034 (Sw4, PS1 Faulty, RPS NotExist) is notFunctioning | 'temp_1006'=24;60;;; 'temp_2006'=25;60;;; 'temp_3006'=24;60;;; 'temp_4006'=22;60;;;

At the switch cli looks fine:

MXXX8#sh env power all
SW  PID                 Serial#     Status           Sys Pwr  PoE Pwr  Watts
--  ------------------  ----------  ---------------  -------  -------  -----
1A  C3KX-PWR-715WAC     LITXFD  OK              Good     Good     715/0
1B  Not Present       
2A  C3KX-PWR-715WAC     LIXBPG  OK              Good     Good     715/0
2B  Not Present       
3A  C3KX-PWR-715WAC     LITXNE  OK              Good     Good     715/0
3B  Not Present       
4A  C3KX-PWR-715WAC     LITXQ7  OK              Good     Good     715/0
4B  Not Present       

MXXX8#sh env power switch 4
SW  PID                 Serial#     Status           Sys Pwr  PoE Pwr  Watts
--  ------------------  ----------  ---------------  -------  -------  -----
4A  C3KX-PWR-715WAC     LITX7  OK              Good     Good     715/0
4B  Not Present       

MXXX8#sh env rps 
SW  Status          RPS Name          RPS Serial#  RPS Port#
--  -------------   ----------------  -----------  ---------
1   Not Present     <>
2   Not Present     <>
3   Not Present     <>
4   Not Present     <>

MXXX8#sh env all
FAN 1 is OK
FAN 2 is OK
FAN PS-1 is OK
FAN PS-2 is NOT PRESENT
TEMPERATURE is OK
Temperature Value: 24 Degree Celsius
Temperature State: GREEN
Yellow Threshold : 46 Degree Celsius
Red Threshold    : 60 Degree Celsius
SW  PID                 Serial#     Status           Sys Pwr  PoE Pwr  Watts
--  ------------------  ----------  ---------------  -------  -------  -----
1A  C3KX-PWR-715WAC     LXXD  OK              Good     Good     715/0
1B  Not Present       
2A  C3KX-PWR-715WAC     LIXG  OK              Good     Good     715/0
2B  Not Present       
3A  C3KX-PWR-715WAC     LIXE  OK              Good     Good     715/0
3B  Not Present       
4A  C3KX-PWR-715WAC     LIX7  OK              Good     Good     715/0
4B  Not Present       

SW  Status          RPS Name          RPS Serial#  RPS Port#
--  -------------   ----------------  -----------  ---------
1   Not Present     <>
2   Not Present     <>
3   Not Present     <>
4   Not Present     <>

HW: Cisco WS-C3750X-24P
IOS: Version 12.2(55)SE7

**Comment by lausser** [comment]
check_nwc_health simply repeats what it gets via snmp queries. If the CLI says something different than SNMP, then this looks like a bug.
You might do a 
snmpwalk ...... ip_of_the_device 1.3.6.1.4.1.9.9.13.1.5.1.3
where you'll get 3x "normal" and 1x "notFunctioning" and present this to the Cisco Support.

**Comment by hamidsadegh** [comment]
It seams like a Cisco Bug.
here is the link:
https://bst.cloudapps.cisco.com/bugsearch/bug/CSCui31295
