### ISSUE TITLE
Use of uninitialized value in pattern match

### ISSUE THREAD

**Issue by arcadesolutions** [lausser/check_nwc_health#59]
Just upgraded to the newest 5.1, there seems to be an issue with the mode interface-usage as i always get the the output like this:

```

check_nwc_health --hostname 1.1.1.1--mode interface-usage --community test --name Bundle-Ether1401 --units MBi

Use of uninitialized value in pattern match (m//) at ./check_nwc_health line 1788.
Use of uninitialized value in pattern match (m//) at ./check_nwc_health line 1788.
OK - interface Bundle-Ether1401 (alias * to bun1500.ZHHARG1Esr002 L2 *) usage is in:1.38% (131.18MBi/s) out:0.46% (43.90MBi/s) | 'Bundle-Ether1401_usage_in'=1.38%;80;90;0;100 'Bundle-Ether1401_usage_out'=0.46%;80;90;0;100 'Bundle-Ether1401_traffic_in'=131.18;7629.3945;8583.0688;0;9536.7432 'Bundle-Ether1401_traffic_out'=43.90;7629.3945;8583.0688;0;9536.7432
```

The exact same command worked fine with version 3.5.1, i'm not that familiar with perl to see whats the problem here.

Thanks
Reto

**Comment by lausser** [comment]
Hi,
can you please run
check_nwc_health --hostname 1.1.1.1--mode walk --community test 
pipe the output in a bash and mail me the resulting snmpwalk-file to gerhard.lausser@consol.de
I can then simulate and debug.
Gerhard

**Comment by lausser** [comment]
Hi,
make a "git pull;autoreconf;./configure;make" and try it again. It should be ok now.
Gerhard

**Comment by arcadesolutions** [comment]
Hey,

I pulled the newst 5.2.1 version and tried it again, unfortunately, the error is still the same with interface-usage, can i help in anyway with some more debug output?

Regards
Reto

Von: Gerhard Lausser [mailto:notifications@github.com]
Gesendet: Montag, 15. Februar 2016 21:03
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Reto Zeder <reto.zeder@arcade.ch>
Betreff: Re: [check_nwc_health] Use of uninitialized value in pattern match (#59)


Hi,
make a "git pull;autoreconf;./configure;make" and try it again. It should be ok now.
Gerhard

**Comment by lausser** [comment]
Ah, i thought it would update the GLPlugin subrepository automatically. And the bugfix is in GLPlugin.
git clone --recursive https://github.com/lausser/check_nwc_health
or
cd check_nwc_health; git pull
git submodule init
git submodule update

**Comment by arcadesolutions** [comment]
Perfect, thank you very much, it works.

Best Regards
Reto

Von: Gerhard Lausser [mailto:notifications@github.com]
Gesendet: Dienstag, 16. Februar 2016 10:18
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Cc: Reto Zeder <reto.zeder@arcade.ch>
Betreff: Re: [check_nwc_health] Use of uninitialized value in pattern match (#59)


Ah, i thought it would update the GLPlugin subrepository automatically. And the bugfix is in GLPlugin.
git clone --recursive https://github.com/lausser/check_nwc_health
or
cd check_nwc_health; git pull
git submodule init
git submodule update
