### ISSUE TITLE
Bug in 5.2.2: Checkpoint Management Appliance cpu and memory checks not working

### ISSUE THREAD

**Issue by Napsty** [lausser/check_nwc_health#60]
Since using version 5.2.2, the cpu-load and memory-usage checks stopped working on a Checkpoint Management Appliance (basically a Linux server running some daemons).

```
$ ./check_nwc_health --version
check_nwc_health $Revision: 5.2.2 $ [http://labs.consol.de/nagios/check_nwc_health]

$ ./check_nwc_health --hostname mgmtserver --protocol 3 --username nagios --authpassword XXX --authprotocol md5 --mode cpu-load -v -v -v
I am a Linux u020sys0 2.6.18-92cp #1 SMP Tue Dec 1 00:01:24 IST 2015 i686
Model Linux u020sys0 2.6.18-92cp #1 SMP Tue Dec 1 00:01:24 IST 2015 i686 is not implemented
```

Tested it with an older version (4.6.1) and it works here:

```
$ ./check_nwc_health.4.6.1 --version
check_nwc_health.4.6.1 $Revision: 4.6.1 $ [http://labs.consol.de/nagios/check_nwc_health]

$ ./check_nwc_health.4.6.1 --hostname mgmtserver --protocol 3 --username nagios --authpassword XXX --authprotocol md5 --mode cpu-load -v -v -v
I am a Linux u020sys0 2.6.18-92cp #1 SMP Tue Dec 1 00:01:24 IST 2015 i686
[CPUSUBSYSTEM]
procUsage: 93
info: cpu usage is 93.00%

CRITICAL - cpu usage is 93.00%
checking cpus
cpu usage is 93.00% | 'cpu_usage'=93%;80;90;0;100
```

This is most likely due to the different Checkpoint detection method in commit 3560626f7ab9509d6f3f8e45d43f6909e980307b.

**Comment by lausser** [comment]
Does it still not work?

**Comment by Napsty** [comment]
Just tested it with the pulled master from March 11 2015:

	$ ./check_nwc_health -V
	check_nwc_health $Revision: 5.3.2 $ [http://labs.consol.de/nagios/check_nwc_health]

Still the same:

	$ ./check_nwc_health --hostname mgmtserver --protocol 3 --username nagios --authpassword XXX --authprotocol md5 --mode cpu-load -v -v -v
	I am a Linux fwml001 2.6.18-92cp #1 SMP Tue Dec 1 00:01:24 IST 2015 i686
	Model Linux fwml001 2.6.18-92cp #1 SMP Tue Dec 1 00:01:24 IST 2015 i686 is not implemented

With the referenced pull requests it works again.

**Comment by Napsty** [comment]
Just tested this today again with 5.9.0.1:

	$ ./check_nwc_health -V
	check_nwc_health $Revision: 5.9.0.1 $ [http://labs.consol.de/nagios/check_nwc_health]

	$ ./check_nwc_health --hostname mgmtserver --protocol 3 --username nagios --authpassword XXX --authprotocol md5 --mode cpu-load 
	OK - cpu usage is 6.00% | 'cpu_usage'=6%;80;90;0;100

Closing :+1:
