### ISSUE TITLE
Option --selectedthresholds not available

### ISSUE THREAD

**Issue by cioby23** [lausser/check_nwc_health#63]
I just checked the documentation and compiled the latest version for check_nwc_health (v5.3) but the  **--selectedthresholds** option is not available for use.

**Comment by lausser** [comment]
it's called "selectedperfdata". I wonder when it was no longer called 
selectedthresholds (which is a misleading name). There are still slides out 
there from a presentation in 2014.



[lausser@HULSE check_nwc_health]$ 
plugins-scripts/check_nwc_health --hostname 10.0.12.114 --community 
cisco/cisco-cat6509  --mode hardware-health

OK - environmental hardware working fine | 'temp_100050'=35;65;;; 
'temp_100051'=36;65;;; 'temp_40010'=31;115;;; 'temp_40020'=34;115;;; 
'temp_40030'=30;115;;; 'temp_60010'=45;85;;; 'temp_60011'=34;65;;; 
'temp_60020'=30;95;;; 'temp_60021'=30;70;;; 'temp_60030'=35;100;;; 
'temp_60031'=29;70;;; 'temp_60050'=43;85;;; 'temp_60051'=29;80;;; 
'temp_60054'=62;105;;; 'temp_60055'=45;110;;; 'temp_60056'=57;110;;; 
'temp_90010'=38;80;;; 'temp_90011'=33;75;;; 'temp_90050'=38;75;;; 
'temp_90051'=31;65;;;



[lausser@HULSE check_nwc_health]$ 
plugins-scripts/check_nwc_health --hostname 10.0.12.114 --community 
cisco/cisco-cat6509  --mode hardware-health --selectedperfdata 'temp.*1$'

OK - environmental hardware working fine | 'temp_100051'=36;65;;; 
'temp_60011'=34;65;;; 'temp_60021'=30;70;;; 'temp_60031'=29;70;;; 
'temp_60051'=29;80;;; 'temp_90011'=33;75;;; 'temp_90051'=31;65;;;



Von: cioby23 [mailto:notifications@github.com]
Gesendet: Donnerstag, 25. Februar 2016 10:35
An: lausser/check_nwc_health <check_nwc_health@noreply.github.com>
Betreff: [check_nwc_health] Option --selectedthresholds not available (#63)



I just checked the documentation and compiled the latest version for 
check_nwc_health (v5.3) but the --selectedthresholds option is not available 
for use.

—
Reply to this email directly or view it on GitHub 
<https://github.com/lausser/check_nwc_health/issues/63> . 
<https://github.com/notifications/beacon/AAMJOKdDueArO5K-Nr27QuyAK3Ef2aKkks5pnsJCgaJpZM4Hikmo.gif>

**Comment by cioby23** [comment]
Thanks it works.
