### ISSUE TITLE
Error  mode hardware health Nortel 5632

### ISSUE THREAD

**Issue by trentasis** [lausser/check_nwc_health#71]
Hi,

We have tested check_nwc_health with nortel switchs and are working perfect, only detected a problem with nortel 5632 in hardware health mode

we have two 5632 and output that we receive same error in both machines

[root@server check_nwc_health]# ./check_nwc_health --hostname 192.168.168.11 --community public --mode hardware-health
UNKNOWN - component 4.12.0/Unavailable status is notAvail (admin enable)
[root@server check_nwc_health]# ./check_nwc_health --hostname 192.168.168.12 --community public --mode hardware-health
UNKNOWN - component 4.12.0/Unavailable status is notAvail (admin enable)

we have investigated and seems that nortel hardware are ok, but check_nwc is reporting an incorrecte values of PSU that doesn't exist

I have found this:
http://www.mibdepot.com/cgi-bin/getmib3.cgi?win=mib_a&r=avaya&f=S5-REG-MIB.mib&v=v2&t=tree
**s5ChasComERS5632-FDPwr-None	OBJ ID		 	1.3.6.1.4.1.45.1.6.1.3.8.108.3 --> ERROR**
s5ChasComERS5632-FDPwr-AC-DC-12V-300W	OBJ ID		 	1.3.6.1.4.1.45.1.6.1.3.8.108.4 --> OK

It seems that 4.12 is 1.3.6.1.4.1.45.1.6.1.3.8.108.3 related with power, but this machine has two powers  main and redund, .4, and .3 is the problem doesn't exist and report a failure?

check_nwc in debug mode show:
[COMP_4.10.0]
s5ChasComAdminState: enable
s5ChasComBaseNumPorts: 0
s5ChasComDescr: AC-DC-12V-300W
s5ChasComGroupMap: 0
s5ChasComGrpIndx: 4
s5ChasComIndx: 10
s5ChasComIpAddress: 0.0.0.0
s5ChasComLocation: 
s5ChasComLstChng: 0
s5ChasComMaxSubs: 0
s5ChasComNumSubs: 0
s5ChasComOperState: normal
s5ChasComRelPos: 0
s5ChasComSerNum: 
s5ChasComShortDescr: AC-DC-12V-300W
s5ChasComSubIndx: 0
s5ChasComTotalNumPorts: 0
s5ChasComType: 1.3.6.1.4.1.45.1.6.1.3.8.108.4
s5ChasComVer: 
info: component 4.10.0/AC-DC-12V-300W status is normal (admin enable)

[COMP_4.11.0]
s5ChasComAdminState: enable
s5ChasComBaseNumPorts: 0
s5ChasComDescr: AC-DC-12V-300W
s5ChasComGroupMap: 0
s5ChasComGrpIndx: 4
s5ChasComIndx: 11
s5ChasComIpAddress: 0.0.0.0
s5ChasComLocation: 
s5ChasComLstChng: 0
s5ChasComMaxSubs: 0
s5ChasComNumSubs: 0
s5ChasComOperState: normal
s5ChasComRelPos: 0
s5ChasComSerNum: 
s5ChasComShortDescr: AC-DC-12V-300W
s5ChasComSubIndx: 0
s5ChasComTotalNumPorts: 0
s5ChasComType: 1.3.6.1.4.1.45.1.6.1.3.8.108.4
s5ChasComVer: 
info: component 4.11.0/AC-DC-12V-300W status is normal (admin enable)

[COMP_4.12.0]
s5ChasComAdminState: enable
s5ChasComBaseNumPorts: 0
s5ChasComDescr: Unavailable
s5ChasComGroupMap: 0
s5ChasComGrpIndx: 4
s5ChasComIndx: 12
s5ChasComIpAddress: 0.0.0.0
s5ChasComLocation: 
s5ChasComLstChng: 0
s5ChasComMaxSubs: 0
s5ChasComNumSubs: 0
s5ChasComOperState: notAvail
s5ChasComRelPos: 0
s5ChasComSerNum: 
s5ChasComShortDescr: Unavailable
s5ChasComSubIndx: 0
s5ChasComTotalNumPorts: 0
s5ChasComType: 1.3.6.1.4.1.45.1.6.1.3.8.108.3
s5ChasComVer: 
info: component 4.12.0/Unavailable status is notAvail (admin enable)

4.10 and 4.11 are correct powers working, and 4.12 I think that is the problme that reports incorrecte hardware health.

How can I make an exclusion or svole this problem to show correct hardware health in both machines?

Thanks

**Comment by lausser** [comment]
--blacklist COMP_4.12.0
Can it be administratively disabled? "s5ChasComAdminState: enable" is an oid which can be written. So the cleanest way would be do set "disable" here. notAvail  is more like an error message, the snmp Agent is not able to get a Status of the component. If check_nwc_health would treat notAvail  like disabled, then it could happen that all of the components become notAvail (caused by whatever Problem) and no one would notice anything.

**Comment by trentasis** [comment]
Thanks!!
with --blacklist COMP_4.12.0 works perfect!
