### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tbaror** [lausser/check_nwc_health#80]
Hi ,
I am trying to build plugin under Ubuntu 14.04 64 i get following error during "make" below
Any idea how to solve it ?
Thanks
`Making all in plugins-scripts
make[1]: Entering directory `/root/check_nwc_health/plugins-scripts'
make[1]: *** No rule to make target `../GLPlugin/lib/Monitoring/GLPlugin/SNMP/MibsAndOids/VRRPMIB.pm', needed by `check_nwc_health'.  Stop.
make[1]: Leaving directory `/root/check_nwc_health/plugins-scripts'
make: *** [all-recursive] Error 1
`

**Comment by lausser** [comment]
cd GLPlugin; git checkout master; git pull; cd ..; git pull
