### ISSUE TITLE
Nortel 4548GT-PWR with failed fan not displayed

### ISSUE THREAD

**Issue by trentasis** [lausser/check_nwc_health#85]
Hi,

I have a Nortel 4548GT-PWR that is showing a fan 3 in failed state, with cli, running "show envir" appears as failed

Running hardware-health mode appear all OK, and output in debug mode is:

 ./check_nwc_health --hostname 192.168.170.107 --community public --mode hardware-health -v
I am a Ethernet Routing Switch 4548GT-PWR    HW:06       FW:5.3.0.3   SW:v5.3.2.007 BN:07 (c) Nortel Networks
OK - environmental hardware working fine
component 3.10.0/48 ports 10/100/1000 BaseT with PoE and 4 shared SFP ports status is normal (admin enable)
component 3.10.1/ status is removed (admin enable)
component 3.10.2/ status is removed (admin enable)
component 3.10.3/SX GBIC status is normal (admin enable)
component 3.10.4/SX GBIC status is normal (admin enable)
component 3.10.5/ status is normal (admin enable)
component 4.10.0/Primary Power Supply status is normal (admin enable)
component 4.11.0/Redundant Power Supply status is removed (admin enable)
component 5.10.0/Temperature Sensor status is normal (admin enable)
component 6.10.0/Internal Fan 1 status is normal (admin enable)
component 6.11.0/Internal Fan 2 status is normal (admin enable)
component 6.12.0/Internal Fan 3 status is warning (admin enable)
component 6.13.0/Internal Fan 4 status is normal (admin enable)
component 8.1.0/48 ports 10/100/1000 BaseT with PoE and 4 shared SFP ports status is normal (admin enable)

and 6.12 (failed fan)
[COMP_6.12.0]
s5ChasComAdminState: enable
s5ChasComBaseNumPorts: 0
s5ChasComDescr: Internal Fan 3
s5ChasComGroupMap: 0
s5ChasComGrpIndx: 6
s5ChasComIndx: 12
s5ChasComIpAddress: 0.0.0.0
s5ChasComLocation:
s5ChasComLstChng: 0
s5ChasComMaxSubs: 0
s5ChasComNumSubs: 0
s5ChasComOperState: warning
s5ChasComRelPos: 0
s5ChasComSerNum:
s5ChasComShortDescr: Internal Fan 3
s5ChasComSubIndx: 0
s5ChasComTotalNumPorts: 0
s5ChasComType: 1.3.6.1.4.1.45.1.6.1.3.10.91.1
s5ChasComVer:
info: component 6.12.0/Internal Fan 3 status is warning (admin enable)

Why is shown OK when a warning is showed in debug mode?
How can I solve this?

Thanks

**Comment by lausser** [comment]
Please send me an snmpwalk

**Comment by trentasis** [comment]
Sended by private mail snmpwalk

**Comment by lausser** [comment]
good catch. It was a copy&paste-error. Now you get:
WARNING - component 6.12.0/Internal Fan 3 status is warning (admin enable)
https://labs.consol.de/nagios/check_nwc_health/index.html with the download link should be updated in a few minutes.

**Comment by trentasis** [comment]
Thanks and great job!!
