### ISSUE TITLE
error compile from sources

### ISSUE THREAD

**Issue by trentasis** [lausser/check_nwc_health#99]
I have downloaded zip from master branch and tried to compile without success:

 autoconf
 ./configure
./configure: line 1757: syntax error near unexpected token `1.9'
./configure: line 1757: `AM_INIT_AUTOMAKE(1.9 tar-pax)'

where is the problem?

thanks

**Comment by trentasis** [comment]
with # autoconf
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:58: error: possibly undefined macro: AM_CONDITIONAL



and with autoreconf receive
# autoreconf
Can't exec "aclocal": No existe el fichero o el directorio at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No existe el fichero o el directorio


and with ./configure
# ./configure
./configure: line 1757: syntax error near unexpected token `1.9'
./configure: line 1757: `AM_INIT_AUTOMAKE(1.9 tar-pax)'


Tried in centos 6.6, where is the problem?

Thanks

**Comment by lausser** [comment]
No problem with CentOS 6.8
[lausser@jump tmp]$ wget https://github.com/lausser/check_nwc_health/archive/master.zip
--2016-07-16 22:32:21--  https://github.com/lausser/check_nwc_health/archive/master.zip
Resolving github.com... 192.30.253.113
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/lausser/check_nwc_health/zip/master [following]
--2016-07-16 22:32:21--  https://codeload.github.com/lausser/check_nwc_health/zip/master
Resolving codeload.github.com... 192.30.253.120
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6359836 (6.1M) [application/zip]
Saving to: “master.zip”

100%[===========================================================================================================================>] 6,359,836   4.76M/s   in 1.3s

2016-07-16 22:32:23 (4.76 MB/s) - “master.zip” saved [6359836/6359836]

[lausser@jump tmp]$ unzip -q master.zip
[lausser@jump tmp]$ cd check_nwc_health-master/
[lausser@jump check_nwc_health-master]$ autoreconf
Makefile.am:4: shell which dos2unix || which fromdos: non-POSIX variable name
Makefile.am:4: (probably a GNU make extension)
[lausser@jump check_nwc_health-master]$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking for sh... /bin/sh
checking for perl... /usr/bin/perl
configure: creating ./config.status
config.status: creating Makefile
config.status: creating plugins-scripts/Makefile
config.status: creating plugins-scripts/subst
                       --with-perl: /usr/bin/perl
                --with-nagios-user: nagios
               --with-nagios-group: nagios
              --disable-standalone:
[lausser@jump check_nwc_health-master]$ cat /etc/redhat-release
CentOS release 6.8 (Final)
[lausser@jump check_nwc_health-master]$

**Comment by trentasis** [comment]
Thanks, installed automake and now works
